namespace PrincesPalace
{
    // WHERE THE MELEE CONTACT CUES LIVE, all in one place.
    //
    // Three different files fire these -- StaticSwing plays the
    // whoosh at the top of the crouch, FightController.PlayContactFx plays the
    // two frame sequences and the thud at the impact instant -- and they have
    // to agree about which asset is which. A path spelled twice is a cue that
    // goes silent on one of the two call sites and nowhere reports it, which
    // is the failure StanceSpriteImporter's own header records twice over.
    //
    // The DURATIONS are here rather than authored per skill on purpose. A
    // spell's vfxSeconds belongs in skills.json beside its damage because a
    // designer tunes the two together; a plain swing has no content row of its
    // own, and inventing one for the pilot would be the "fourth format" the
    // static-art plan explicitly says not to build before the pilot is judged.
    internal static class ContactCues
    {
        // Generated by tools/make_contact_fx.py, six frames each, f0..f5.
        internal const string SlashArcPath = "Vfx/slash_arc";
        internal const string ImpactBurstPath = "Vfx/impact_burst";

        // The arc is the READING of the blow and the burst is its punctuation,
        // so the burst outlives it: the sweep is gone by the time the eye has
        // found the target, and what is left holding the moment is the flash
        // of debris. Both well inside the beat's own 0.45s budget, because a
        // contact effect that outlasts its beat is still on screen when the
        // next blow lands.
        internal const float SlashSeconds = 0.18f;
        internal const float BurstSeconds = 0.24f;

        // The square the effects are fitted into, BEFORE the target slot's
        // depth scale is applied (see FightController.ContactBoxFor). Smaller
        // than SpellPresentation.DefaultSize's 380 because a swing lands ON a
        // body rather than erupting around it -- at 380 the arc read as a
        // second creature standing where the first one was.
        internal const float BoxSize = 260f;

        // PLACEHOLDERS, synthesised by tools/make_contact_fx.py --audio. Both
        // are marked as such in Resources/Audio/README.md; nothing about the
        // timing above depends on the actual recordings that replace them.
        internal const string WhooshClipPath = "Audio/Sfx/melee_whoosh_placeholder";
        internal const string ThudClipPath = "Audio/Sfx/melee_thud_placeholder";
    }
}
