using System;
using System.IO;
using UnityEditor;
using UnityEngine;

// Bakes the shapes a flat uGUI Image cannot draw into COMMITTED PNG assets.
//
// v1 generated these at runtime and assigned them from a component marked
// [ExecuteAlways], which meant the Edit Mode scene build assigned a sprite that
// was not an asset. Unity's response to that is to serialise the texture INTO
// the scene: measured on v2's main menu, 104 scene-local sprite references and
// an embedded Texture2D, accounting for most of a 624 KB scene file.
//
// It worked, but everything about it is bad: the texture is undiffable, it is
// duplicated once per scene that uses it, it cannot be inspected or replaced,
// and it makes a text-format scene file mostly binary noise.
//
// Baked PNGs are ordinary assets. One GUID, referenced by every scene, visible
// in a diff, and the same rule as everything else here: generated by a tool you
// can re-run, never hand-authored.
public static class ProceduralSpriteBaker
{
    public const string GeneratedDir = "Assets/_Project/Art/Generated";
    private const int Size = 128;

    [MenuItem("Prince's Palace/Bake Procedural Sprites")]
    public static void BakeAll()
    {
        Directory.CreateDirectory(GeneratedDir);

        // White at the centre fading smoothly to fully transparent at the edge.
        // Tinted through Image.color at every use site, which is why one asset
        // serves stars, lanterns, window bloom, motes and mist alike.
        Bake("radial_glow", dist => 1f - Smoothstep(Mathf.Clamp01(dist)));

        // A flat disc with a thin antialiased edge - a coin, an orb, anything
        // that must not render as a square.
        Bake("solid_circle", dist => 1f - Mathf.Clamp01((dist - 0.92f) / 0.08f));

        // A soft annulus: the fight stage's ground contact ring. Hollow, so an
        // actor reads as STANDING inside a mark on the floor rather than on top
        // of a painted disc -- and soft on both edges, because a hard ring at
        // this size reads as a drawn circle rather than as light on the ground.
        Bake("ring_outline", dist =>
        {
            const float centre = 0.72f;
            const float halfWidth = 0.20f;
            float offset = Mathf.Abs(Mathf.Clamp01(dist) - centre);
            return 1f - Smoothstep(Mathf.Clamp01(offset / halfWidth));
        });

        AssetDatabase.SaveAssets();
        Debug.Log("BUILD-COMPLETE: ProceduralSpriteBaker");
    }

    private static float Smoothstep(float x) => x * x * (3f - 2f * x);

    // A radially symmetric shape: alpha as a function of distance from centre,
    // white throughout so every use site can tint it.
    private static void Bake(string name, Func<float, float> alphaAtDistance)
    {
        var texture = new Texture2D(Size, Size, TextureFormat.RGBA32, false);
        var pixels = new Color32[Size * Size];

        for (int y = 0; y < Size; y++)
        {
            for (int x = 0; x < Size; x++)
            {
                float nx = (x + 0.5f) / Size * 2f - 1f;
                float ny = (y + 0.5f) / Size * 2f - 1f;
                float alpha = Mathf.Clamp01(alphaAtDistance(Mathf.Sqrt(nx * nx + ny * ny)));
                pixels[y * Size + x] = new Color32(255, 255, 255, (byte)Mathf.RoundToInt(alpha * 255f));
            }
        }

        texture.SetPixels32(pixels);
        texture.Apply();
        WritePng($"{GeneratedDir}/{name}.png", texture);
    }

    // Encode, compare, write, import. One place that knows the importer
    // settings a Sprite needs.
    private static void WritePng(string path, Texture2D texture)
    {
        var png = texture.EncodeToPNG();
        UnityEngine.Object.DestroyImmediate(texture);

        // Byte-compare before writing: an unchanged PNG must not be rewritten,
        // or every build churns the file and every diff is noise.
        if (File.Exists(path) && File.ReadAllBytes(path).AsSpan().SequenceEqual(png))
        {
            return;
        }

        File.WriteAllBytes(path, png);
        AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceSynchronousImport);

        // Without Sprite + alphaIsTransparency, LoadAssetAtPath<Sprite> returns
        // null with no error anywhere - the failure that shipped a spell playing
        // nothing for weeks in v1.
        var importer = AssetImporter.GetAtPath(path) as TextureImporter;
        if (importer != null)
        {
            importer.textureType = TextureImporterType.Sprite;
            importer.spriteImportMode = SpriteImportMode.Single;
            importer.alphaIsTransparency = true;
            importer.mipmapEnabled = false;
            importer.SaveAndReimport();
        }

        Debug.Log($"[ProceduralSpriteBaker] baked {path}");
    }
}
