using System;
using System.IO;
using UnityEditor;
using UnityEngine;

// Bakes the shapes a flat uGUI Image cannot draw into COMMITTED PNG assets.
//
// v1 generated these at runtime and assigned them from a component marked
// [ExecuteAlways], which meant the Edit Mode scene build assigned a sprite that
// was not an asset. Unity's response to that is to serialise the texture INTO
// the scene: measured on v2's main menu, 104 scene-local sprite references and
// an embedded Texture2D, accounting for most of a 624 KB scene file.
//
// It worked, but everything about it is bad: the texture is undiffable, it is
// duplicated once per scene that uses it, it cannot be inspected or replaced,
// and it makes a text-format scene file mostly binary noise.
//
// Baked PNGs are ordinary assets. One GUID, referenced by every scene, visible
// in a diff, and the same rule as everything else here: generated by a tool you
// can re-run, never hand-authored.
public static class ProceduralSpriteBaker
{
    public const string GeneratedDir = "Assets/_Project/Art/Generated";
    private const int Size = 128;

    [MenuItem("Prince's Palace/Bake Procedural Sprites")]
    public static void BakeAll()
    {
        Directory.CreateDirectory(GeneratedDir);

        // White at the centre fading smoothly to fully transparent at the edge.
        // Tinted through Image.color at every use site, which is why one asset
        // serves stars, lanterns, window bloom, motes and mist alike.
        Bake("radial_glow", dist => 1f - Smoothstep(Mathf.Clamp01(dist)));

        // A flat disc with a thin antialiased edge - a coin, an orb, anything
        // that must not render as a square.
        Bake("solid_circle", dist => 1f - Mathf.Clamp01((dist - 0.92f) / 0.08f));

        // A soft annulus: the fight stage's ground contact ring. Hollow, so an
        // actor reads as STANDING inside a mark on the floor rather than on top
        // of a painted disc -- and soft on both edges, because a hard ring at
        // this size reads as a drawn circle rather than as light on the ground.
        Bake("ring_outline", dist =>
        {
            const float centre = 0.72f;
            const float halfWidth = 0.20f;
            float offset = Mathf.Abs(Mathf.Clamp01(dist) - centre);
            return 1f - Smoothstep(Mathf.Clamp01(offset / halfWidth));
        });

        // The talent tree's edge kit. Soft along its SHORT axis and uniform
        // along its long one, so a quad stretched between two orbs fades at
        // its sides instead of ending on a hard 10px band -- which is what
        // makes an edge read as a lit crack rather than as a drawn rectangle.
        //
        // The same falloff ProceduralSprites.SoftEdgeStripe builds at runtime,
        // committed here because the emitter needs a real asset with a GUID.
        BakeGradient("soft_edge_stripe", 64,
            ny => (1f, 1f - Smoothstep(Mathf.Abs(ny * 2f - 1f))));

        BakeRarityBurst();
        BakeBar();
        BakeScrim();
        BakeEmber();

        AssetDatabase.SaveAssets();
        Debug.Log("BUILD-COMPLETE: ProceduralSpriteBaker");
    }

    // The glow that spins behind an offered item, tinted per rarity.
    //
    // GENERATED rather than painted, and here that is the better tool rather
    // than a placeholder standing in for one. The brief asks for three things
    // at once: rays that feather with no hard edge anywhere, a fade to nothing
    // WELL INSIDE the canvas so rotation cannot clip a ray at the diagonals,
    // and radial symmetry good enough that a spin does not wobble. A diffusion
    // model holds those by luck; arithmetic holds them by construction.
    //
    // White, so RarityColors tints one asset six ways.
    private static void BakeRarityBurst()
    {
        const int Rays = 29;              // prime, so no ray sits opposite another
        const float CoreRadius = 0.13f;   // the diffuse bloom in the middle
        const float FadeBy = 0.78f;       // gone by here, clear of every corner

        // Deterministic from the index. The baker must produce the same bytes
        // every run or WritePng's compare-before-write is defeated and every
        // build churns the file.
        var angle = new float[Rays];
        var width = new float[Rays];
        var reach = new float[Rays];

        for (int i = 0; i < Rays; i++)
        {
            // Evenly spaced then nudged, so the spacing reads as light rather
            // than as a cog.
            angle[i] = i / (float)Rays * Mathf.PI * 2f + Mathf.Sin(i * 12.9898f) * 0.06f;

            // Alternating thick and thin is what makes a burst read as light
            // instead of as a star polygon.
            width[i] = Mathf.Lerp(0.020f, 0.055f, Frac(i * 0.7548f));

            // UNEVEN LENGTHS. With every ray the same, a spin has nothing to
            // announce itself with and the whole thing looks static.
            reach[i] = Mathf.Lerp(0.42f, FadeBy, Frac(i * 0.3247f));
        }

        BakeTrackMarks();

        BakeGlow("rarity_burst", 1024, (nx, ny) =>
        {
            float radius = Mathf.Sqrt(nx * nx + ny * ny);
            if (radius >= FadeBy) return 0f;

            float theta = Mathf.Atan2(ny, nx);

            // The core: a bloom with no edge of its own.
            float value = Mathf.Exp(-(radius * radius) / (CoreRadius * CoreRadius)) * 0.9f;

            for (int i = 0; i < Rays; i++)
            {
                float delta = Mathf.Abs(Mathf.DeltaAngle(theta * Mathf.Rad2Deg, angle[i] * Mathf.Rad2Deg))
                              * Mathf.Deg2Rad;

                // Gaussian across the ray, so it has no sides.
                float across = Mathf.Exp(-(delta * delta) / (width[i] * width[i]));
                if (across < 0.004f) continue;

                // And squared along it, so the tip dissolves rather than stops.
                float along = Mathf.Clamp01(1f - radius / reach[i]);
                value += across * along * along * 0.85f;
            }

            return Mathf.Clamp01(value);
        });
    }

    // ---- the reward track's marks -------------------------------------------
    //
    // FIVE SHAPES, NOT TWELVE. The track pays twelve kinds of reward and every
    // node already carries its name in words, so an icon per kind would be
    // eleven pieces of bespoke art doing what the caption does. What the rail
    // needs instead is to be SCANNABLE without reading -- four grant marks that
    // differ at a glance, and one ring standing for "a capability", which is
    // what every milestone is.
    //
    // Drawn as strokes rather than glyphs on purpose. A tick or a star from the
    // font would rasterise into the dynamic atlas, and that atlas is tracked in
    // git -- AUDIT #47, where any run that draws a new glyph dirties a
    // committed asset.
    private static void BakeTrackMarks()
    {
        const int Size = 128;

        // The claimed tick. Two strokes, the short one falling and the long one
        // rising well past it, which is what makes a tick read as a tick rather
        // than as a bent line.
        BakeGlow("track_tick", Size, (nx, ny) =>
        {
            float d = Mathf.Min(
                SegmentDistance(nx, ny, -0.42f, 0.02f, -0.12f, -0.34f),
                SegmentDistance(nx, ny, -0.12f, -0.34f, 0.46f, 0.38f));

            return Stroke(d, 0.11f);
        });

        // A stat point: one chevron, pointing up.
        BakeGlow("track_stat", Size, (nx, ny) =>
        {
            float d = Mathf.Min(
                SegmentDistance(nx, ny, -0.42f, -0.16f, 0f, 0.30f),
                SegmentDistance(nx, ny, 0f, 0.30f, 0.42f, -0.16f));

            return Stroke(d, 0.12f);
        });

        // Experience: the same chevron twice, because it is the same idea
        // moving faster.
        BakeGlow("track_exp", Size, (nx, ny) =>
        {
            float upper = Mathf.Min(
                SegmentDistance(nx, ny, -0.40f, 0.02f, 0f, 0.42f),
                SegmentDistance(nx, ny, 0f, 0.42f, 0.40f, 0.02f));
            float lower = Mathf.Min(
                SegmentDistance(nx, ny, -0.40f, -0.34f, 0f, 0.06f),
                SegmentDistance(nx, ny, 0f, 0.06f, 0.40f, -0.34f));

            return Mathf.Max(Stroke(upper, 0.10f), Stroke(lower, 0.10f));
        });

        // Max health: a cross. Square-armed rather than a heart, which at 22px
        // is a blob.
        BakeGlow("track_health", Size, (nx, ny) =>
        {
            float d = Mathf.Min(
                SegmentDistance(nx, ny, -0.34f, 0f, 0.34f, 0f),
                SegmentDistance(nx, ny, 0f, -0.34f, 0f, 0.34f));

            return Stroke(d, 0.12f);
        });

        // Prince's Favor: an X.
        //
        // THIRD ATTEMPT, and the first two are worth recording because they
        // failed the same way. A four-point star fades its arms to nothing and
        // rendered as a dot; a filled diamond is crisp but a solid shape nine
        // pixels across is also a dot. What reads at this size is a STROKE --
        // which is why the chevron and the cross were legible from the first
        // capture and this was not. An X is the stroke that is not either of
        // them.
        BakeGlow("track_favor", Size, (nx, ny) =>
        {
            float d = Mathf.Min(
                SegmentDistance(nx, ny, -0.30f, -0.30f, 0.30f, 0.30f),
                SegmentDistance(nx, ny, -0.30f, 0.30f, 0.30f, -0.30f));

            return Stroke(d, 0.11f);
        });
    }

    // Distance from (px,py) to the segment (ax,ay)-(bx,by), in the same
    // normalised space the bake lambdas work in.
    private static float SegmentDistance(float px, float py, float ax, float ay, float bx, float by)
    {
        float vx = bx - ax;
        float vy = by - ay;
        float wx = px - ax;
        float wy = py - ay;

        float lengthSquared = vx * vx + vy * vy;
        float t = lengthSquared <= 0f ? 0f : Mathf.Clamp01((wx * vx + wy * vy) / lengthSquared);

        float dx = wx - vx * t;
        float dy = wy - vy * t;
        return Mathf.Sqrt(dx * dx + dy * dy);
    }

    // A stroke of `halfWidth`, antialiased over the outer fifth of it so the
    // marks do not read as pixel art beside painted UI.
    private static float Stroke(float distance, float halfWidth)
    {
        float edge = halfWidth * 0.2f;
        return 1f - Smoothstep(Mathf.Clamp01((distance - (halfWidth - edge)) / edge));
    }

    private static float Frac(float value) => value - Mathf.Floor(value);

    // The experience bar: a recessed channel and the light that fills it.
    //
    // UNIFORM ALONG X, both of them, and that is the whole design decision.
    // The fill is stretched to whatever fraction of the track has been earned,
    // so anything that varies horizontally -- a rounded cap, a highlight at one
    // end -- distorts as the bar grows and, worse, distorts DIFFERENTLY every
    // frame while it animates. All the shaping is vertical; the ends are square
    // and the track's own art supplies the enclosure.
    private static void BakeBar()
    {
        // The channel. Dark, with the light caught along its top lip so it
        // reads as cut into the panel rather than drawn on top of it.
        //
        // The body used to run 0.10..0.22, which is nearly black BEFORE the
        // Reckoning multiplies it by a dark violet tint -- the two darknesses
        // compounded to roughly #08060E and the bar read as a hole punched in
        // the panel rather than as a groove cut into it. Raised so the tint has
        // something to colour: the shading still does the recessing, but the
        // result stays recognisably a surface.
        BakeGradient("bar_track", 64, y =>
        {
            // Light bouncing off the floor of the groove, and the highlight
            // caught on its top lip. Keeping BOTH is what stops a raised level
            // reading as a flat plate: bright, dip, bright is a section through
            // a channel, and a single ramp is not.
            float floorBounce = Mathf.Clamp01(1f - y / 0.22f);
            float lip = Mathf.Exp(-Mathf.Pow((y - 0.94f) / 0.05f, 2f));

            float value = Mathf.Lerp(0.30f, 0.46f, y) + floorBounce * 0.10f;
            return (Mathf.Clamp01(value + lip * 0.42f), 1f);
        });

        // The light the fill throws onto the panel around it.
        //
        // HOLLOW THROUGH THE MIDDLE, which is the whole trick. This is drawn as
        // a child of the fill and therefore ON TOP of it, so any alpha across
        // the bar itself would wash out the thing it is supposed to be lit by.
        // Zero for the width the fill occupies, rising just outside it, gone by
        // the edge -- a halo, not an overlay.
        //
        // The node is inset 12 beyond a 32-tall track, so the fill occupies the
        // middle 32/56 of this texture: everything inside d 0.57 must stay
        // empty, and 0.50 leaves margin for filtering.
        BakeGradient("bar_bloom", 96, y =>
        {
            float d = Mathf.Abs(y - 0.5f) * 2f;                  // 0 centre, 1 edge
            if (d <= 0.5f) return (1f, 0f);

            float t = Mathf.Clamp01((d - 0.5f) / 0.5f);
            float alpha = Smoothstep(Mathf.Clamp01(t / 0.2f)) * Mathf.Pow(1f - t, 1.8f);
            return (1f, alpha);
        });

        // The fill. White so it can be tinted twice from one asset -- once for
        // what was already earned and once, brighter, for what this fight paid.
        BakeGradient("bar_fill", 64, y =>
        {
            // Brightest just under the top edge, falling away downward: a bar
            // lit from above rather than a flat block of colour.
            //
            // The old numbers said bloom and drew a flat white strip. body ran
            // 0.55..0.95 and the bloom added up to 0.55 on top, so everything
            // above y 0.45 clamped to 1 -- five eighths of the bar was one
            // saturated value and the gradient was invisible. A bloom is a
            // bright CORE against something less bright; without the contrast
            // there is nothing to read as light.
            //
            // Lowered and narrowed so the core saturates over roughly a fifth
            // of the height and falls off on both sides of it.
            float bloom = Mathf.Exp(-Mathf.Pow((y - 0.80f) / 0.26f, 2f));
            float body = Mathf.Lerp(0.34f, 0.62f, y);

            // Softened at both edges so it never shows a hard line against the
            // channel it sits in -- and widened with the channel, since a
            // lighter track shows a hard fill edge that a near-black one hid.
            float edge = Mathf.Clamp01(Mathf.Min(y, 1f - y) / 0.10f);

            return (Mathf.Clamp01(body + bloom * 0.62f), edge);
        });
    }

    // The stage scrim: two of its three layers. The third is `radial_glow`,
    // already baked above and simply tinted dark -- a knock-down and a bloom
    // are the same shape, and only the colour differs.
    //
    // BOTH BAKED WHITE, with all the shaping in ALPHA. The scrim's colour is a
    // layout decision and belongs in the screen tree where it can be read next
    // to the palette it has to sit against; baking a dark pixel here would put
    // half the decision in an Editor script and make the tint a multiplier on
    // a number nobody can see.
    private static void BakeScrim()
    {
        // A band across the actor rows. Soft at BOTH edges over a wide
        // falloff: a scrim whose own boundary is visible has become a shape on
        // the screen, which is the one thing it must never be. 0.30 either side
        // leaves a flat 40% core doing the actual separating.
        BakeGradient("scrim_band", 128, y =>
        {
            float edge = Mathf.Clamp01(Mathf.Min(y, 1f - y) / 0.30f);
            return (1f, Smoothstep(edge));
        });

        // The dossier's own wash, brightest along the top edge.
        //
        // A flat ground gave that screen no hierarchy at all: three columns of
        // equal weight on one even field, and nothing telling the eye where to
        // start. Light falling from above is the cheapest fix that is also
        // true to the rest of the game's art -- every portrait and actor in
        // this project is lit from above, so a panel lit the same way sits in
        // the same world rather than looking like a web page behind them.
        //
        // Cubed falloff, not linear. Linear reads as a grey haze over the whole
        // panel; cubed keeps the bottom two thirds honest black and puts the
        // whole of the lift in the top third, where the portrait and the column
        // headings are.
        BakeGradient("dossier_veil", 128, y =>
        {
            float up = Mathf.Clamp01(y);
            return (1f, Smoothstep(up * up * up));
        });

        // Weighted to the bottom of the screen, under the command columns.
        // Squared rather than linear so it stays out of the way through the
        // middle of the frame and only bites where the HUD actually is --
        // a linear ramp put visible grey halfway up the backdrop.
        BakeGradient("scrim_floor", 128, y =>
        {
            float down = Mathf.Clamp01(1f - y);
            return (1f, Smoothstep(down * down));
        });
    }

    // The heat under the Continue arrow.
    //
    // THIS ONE BAKES ITS OWN COLOUR, and that is a departure from the rule the
    // scrim states two methods up -- there, colour is a layout decision and
    // belongs in the tree. Fire is not one colour. A flame is white-hot at the
    // core, orange through the body and deep red at the edge, and no single
    // Image tint can produce that from a greyscale ramp: multiplying white by
    // red gives red everywhere, with a brighter red where the core should be
    // white. The hue ramp is intrinsic to the thing being drawn. Intensity is
    // still the tree's: the node tints alpha and leaves the hues alone.
    //
    // NOT AN ELLIPSE. The brief was "not square or rectangular, it should feel
    // flowing and alive", so the radius is modulated by two out-of-phase sine
    // terms in the angle. Enough to break the silhouette; not so much that it
    // reads as a shape with lobes.
    private static void BakeEmber()
    {
        const int Width = 512;

        // 256 rather than 128. The vertical edge fade below spans a third of
        // the height and is then squeezed into an 88px box on screen, so the
        // ramp has about 29 screen pixels to happen in; at 128 rows it was
        // being reconstructed from 42 texture rows and banded visibly.
        const int Height = 256;
        string path = $"{GeneratedDir}/arrow_ember.png";

        var texture = new Texture2D(Width, Height, TextureFormat.RGBA32, false);
        var pixels = new Color32[Width * Height];

        // The core sits BACK ON THE ARROWHEAD, not at the point, and the whole
        // character of the effect turns on that one number.
        //
        // A core at the point can only ever produce a tail: the arrow is
        // opaque, so nothing behind it shows, and the glow starts where the art
        // stops. Pulled back to -0.18 the core is hidden under the head and
        // what remains visible is the halo AROUND it -- heat running the length
        // of the arrow, top and bottom, brightest at the head and trailing off
        // to the right. That is what makes it embrace the button instead of
        // pointing away from it.
        //
        // Every one of these was settled by compositing against the real arrow
        // and frame rather than reasoned about: a core at the point, a core
        // under the head with a tight vertical spread (a smudge), and a long
        // narrow version that read as jet exhaust, before this.
        const float CoreX = -0.18f;

        // Asymmetric on purpose: the tail runs further right than left.
        const float SpreadRight = 1.10f;
        const float SpreadLeft = 1.00f;

        // WIDE, and this is the other half of the embrace. At 1.25 the glow
        // fell off before it cleared the arrow's own silhouette, so it could
        // never be seen alongside the art -- only past the end of it. At 1.90
        // the falloff is gentle enough that the band of heat is still alive
        // where the arrow's top and bottom edges are.
        const float SpreadY = 1.90f;

        for (int y = 0; y < Height; y++)
        {
            for (int x = 0; x < Width; x++)
            {
                float nx = (x + 0.5f) / Width * 2f - 1f;
                float ny = (y + 0.5f) / Height * 2f - 1f;

                float dx = (nx - CoreX) / (nx >= CoreX ? SpreadRight : SpreadLeft);
                float dy = ny / SpreadY;

                float r = Mathf.Sqrt(dx * dx + dy * dy);
                float angle = Mathf.Atan2(dy, dx);
                float wobble = 1f
                    + 0.13f * Mathf.Sin(angle * 3f + 1.1f)
                    + 0.07f * Mathf.Sin(angle * 5f - 0.4f);
                r /= Mathf.Max(0.35f, wobble);

                float falloff = 1f - Smoothstep(Mathf.Clamp01(r));

                // 1.1, down from a squared falloff and then from 1.3. Each drop
                // buys tail: squared was a dot with nothing coming off it, and
                // anything above about 1.2 loses the far end of the band that
                // now runs alongside the arrow.
                float alpha = Mathf.Pow(falloff, 1.1f);

                // FADE THE OUTER THIRD TO NOTHING, and this is a fix rather
                // than a flourish. SpreadY is 1.90, which means the radial
                // falloff is nowhere near zero by the time it reaches the top
                // and bottom of the texture -- it was still at alpha 64 and 81
                // of 255 at the two edges, so the sprite ended in a hard
                // horizontal line and the glow read as a rectangle laid over
                // the panel. Widening the spread to wrap the arrow is what
                // caused it; the spread is right and the cut was the bug.
                //
                // 0.34, up from a first attempt at 0.10. A tenth was not a
                // gradient: it took alpha from 81 to 1 in six texture rows,
                // which is four pixels once this is squeezed into an 88px box,
                // and four pixels of ramp is still an edge. The fade has to
                // start where the glow is still strong to read as a fade at
                // all.
                //
                // It cannot start much earlier than this without eating the
                // band alongside the arrow that the whole widening was for --
                // the arrow's own silhouette reaches about |ny| 0.68, so the
                // fade begins just outside it.
                //
                // SQUARED, so the ramp leaves the full-strength region gently
                // and arrives at zero steeply. A plain smoothstep put its
                // steepest part in the middle of the ramp, which is exactly
                // where the eye reads a line.
                //
                // Applied on both axes, even though only the vertical one was
                // visibly wrong: the next change to a spread should not be able
                // to reintroduce this.
                float fadeY = Smoothstep(Mathf.Clamp01((1f - Mathf.Abs(ny)) / 0.34f));
                float fadeX = Smoothstep(Mathf.Clamp01((1f - Mathf.Abs(nx)) / 0.10f));
                alpha *= fadeY * fadeY * fadeX;

                // White-hot core -> orange -> deep red, keyed off the same
                // falloff so the hottest pixel is also the brightest.
                float hot = Mathf.Clamp01((falloff - 0.55f) / 0.45f);
                float mid = Mathf.Clamp01(falloff / 0.55f);

                float red = Mathf.Lerp(0.77f, 1f, mid);
                float green = Mathf.Lerp(0.12f, 0.48f, mid) + hot * 0.46f;
                float blue = Mathf.Lerp(0.03f, 0.12f, mid) + hot * 0.62f;

                pixels[y * Width + x] = new Color32(
                    (byte)Mathf.RoundToInt(Mathf.Clamp01(red) * 255f),
                    (byte)Mathf.RoundToInt(Mathf.Clamp01(green) * 255f),
                    (byte)Mathf.RoundToInt(Mathf.Clamp01(blue) * 255f),
                    (byte)Mathf.RoundToInt(Mathf.Clamp01(alpha) * 255f));
            }
        }

        texture.SetPixels32(pixels);
        texture.Apply();
        WritePng(path, texture);
    }

    // A bar-shaped sprite that varies only with height. `shade` returns
    // (brightness, alpha) for a normalised y, 0 at the bottom.
    private static void BakeGradient(string name, int height, Func<float, (float value, float alpha)> shade)
    {
        const int Width = 16;   // uniform across, so this only has to be wide
                                // enough to survive filtering
        string path = $"{GeneratedDir}/{name}.png";

        var texture = new Texture2D(Width, height, TextureFormat.RGBA32, false);
        var pixels = new Color32[Width * height];

        for (int y = 0; y < height; y++)
        {
            var (value, alpha) = shade((y + 0.5f) / height);
            byte channel = (byte)Mathf.RoundToInt(Mathf.Clamp01(value) * 255f);
            byte a = (byte)Mathf.RoundToInt(Mathf.Clamp01(alpha) * 255f);

            for (int x = 0; x < Width; x++)
            {
                pixels[y * Width + x] = new Color32(channel, channel, channel, a);
            }
        }

        texture.SetPixels32(pixels);
        texture.Apply();
        WritePng(path, texture);
    }

    // White pixels whose ALPHA is the intensity. No rim and no signed
    // distance: a glow is a field, not a shape with an edge.
    private static void BakeGlow(string name, int size, Func<float, float, float> intensityAt)
    {
        string path = $"{GeneratedDir}/{name}.png";

        var texture = new Texture2D(size, size, TextureFormat.RGBA32, false);
        var pixels = new Color32[size * size];

        for (int y = 0; y < size; y++)
        {
            for (int x = 0; x < size; x++)
            {
                float nx = (x + 0.5f) / size * 2f - 1f;
                float ny = (y + 0.5f) / size * 2f - 1f;

                float alpha = Mathf.Clamp01(intensityAt(nx, ny));
                pixels[y * size + x] = new Color32(255, 255, 255, (byte)Mathf.RoundToInt(alpha * 255f));
            }
        }

        texture.SetPixels32(pixels);
        texture.Apply();
        WritePng(path, texture);
    }

    private static float Smoothstep(float x) => x * x * (3f - 2f * x);

    // A radially symmetric shape: alpha as a function of distance from centre,
    // white throughout so every use site can tint it.
    private static void Bake(string name, Func<float, float> alphaAtDistance)
    {
        var texture = new Texture2D(Size, Size, TextureFormat.RGBA32, false);
        var pixels = new Color32[Size * Size];

        for (int y = 0; y < Size; y++)
        {
            for (int x = 0; x < Size; x++)
            {
                float nx = (x + 0.5f) / Size * 2f - 1f;
                float ny = (y + 0.5f) / Size * 2f - 1f;
                float alpha = Mathf.Clamp01(alphaAtDistance(Mathf.Sqrt(nx * nx + ny * ny)));
                pixels[y * Size + x] = new Color32(255, 255, 255, (byte)Mathf.RoundToInt(alpha * 255f));
            }
        }

        texture.SetPixels32(pixels);
        texture.Apply();
        WritePng($"{GeneratedDir}/{name}.png", texture);
    }

    // Encode, compare, write, import. One place that knows the importer
    // settings a Sprite needs.
    private static void WritePng(string path, Texture2D texture)
    {
        var png = texture.EncodeToPNG();
        UnityEngine.Object.DestroyImmediate(texture);

        // Byte-compare before writing: an unchanged PNG must not be rewritten,
        // or every build churns the file and every diff is noise.
        if (File.Exists(path) && File.ReadAllBytes(path).AsSpan().SequenceEqual(png))
        {
            return;
        }

        File.WriteAllBytes(path, png);
        AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceSynchronousImport);

        // Without Sprite + alphaIsTransparency, LoadAssetAtPath<Sprite> returns
        // null with no error anywhere - the failure that shipped a spell playing
        // nothing for weeks in v1.
        var importer = AssetImporter.GetAtPath(path) as TextureImporter;
        if (importer != null)
        {
            importer.textureType = TextureImporterType.Sprite;
            importer.spriteImportMode = SpriteImportMode.Single;
            importer.alphaIsTransparency = true;
            importer.mipmapEnabled = false;
            importer.SaveAndReimport();
        }

        Debug.Log($"[ProceduralSpriteBaker] baked {path}");
    }
}
