using System.Collections.Generic;
using System.Linq;
using PrincesPalace.Domain.Content;
using PrincesPalace.Domain.Equipment;

namespace PrincesPalace.Domain.UiKit.Screens
{
    // The character sheet, rebuilt to the "Dossier" handover: identity and pack
    // on the left, a mannequin with its slots in the middle, the numbers on the
    // right.
    //
    // REPLACES CharacterOverlayScreen, and lives inside the system menu's
    // Character and Inventory panes rather than being its own modal -- the two
    // tabs are two doors into this one screen, exactly as C and I are today.
    //
    // Authored AT the menu's 1600x804 content pane and filling it. It used to
    // sit at the handover's own 1360x766, centred, which left 118px of dead
    // margin a side and all three columns stopping short of the floor. Nothing
    // scales: DossierLayout re-proportions the columns and scales the loadout
    // stage as one unit, which is what the handover's rule was protecting.
    //
    // WHAT IS NOT HERE, and why: the handover's Dodge, Carried, Shop prices and
    // Party morale rows are gone. None of them exists in this game -- there is
    // no dodge, no carry weight, no price modifier and no morale -- and printing
    // four numbers with no source would be four lies a player cannot check. The
    // stat list is built from SheetStats.Derived instead, so it is exactly the
    // stats that are real, and adding one later is one entry there.
    public sealed class CharacterDossierScreen
    {
        public const string PortraitKey = "UI/CharacterOverlay/Processed/armour_stand.png";
        // Baked by ProceduralSpriteBaker; "proc:" names a committed PNG rather
        // than a texture generated at runtime.
        public const string VeilKey = "proc:dossier_veil";

        public const string MannequinKey = "UI/CharacterOverlay/Processed/armour_stand.png";

        // The same figure traced to a line, generated by tools/outline_silhouette.py
        // from the fill's own alpha, so the two can never drift apart.
        public const string MannequinOutlineKey =
            "UI/CharacterOverlay/Processed/armour_stand_outline.png";

        // ---- tokens, from the handover's table ----------------------------------

        public const string Rule = "#C8B4DE29";          // rgba(200,180,222,.16)
        public const string RuleSoft = "#C8B4DE12";      // rgba(200,180,222,.07)
        public const string TextHi = "#F4EEFA";
        public const string Text = "#F0E8F8";
        public const string TextDim = "#D6C8E86B";       // rgba(214,200,232,.42)
        public const string TextFaint = "#D6C8E852";     // rgba(214,200,232,.32)
        public const string Accent = "#B9A2D6";
        public const string AccentHi = "#D8C2F0";
        public const string SlotBorder = "#BEA8D652";
        public const string SlotEmptyBorder = "#C8B4DE1F";
        public const string PackGround = "#160E1E";
        public const string Ground = "#120A18FA";

        public UiNode Root;

        public NodeRef Portrait;
        public NodeRef CharacterName;
        public NodeRef SubLine;
        public NodeRef XpFill;
        public NodeRef XpRemaining;
        public NodeRef TrackNext;
        public NodeRef PrevCharacterButton;
        public NodeRef NextCharacterButton;

        public NodeRef SkillsRow;
        public NodeRef TrackRow;
        public NodeRef SkillsCount;
        public NodeRef PackRow;
        public NodeRef PackChevron;

        // The skills panel (owner bug report, 2026-09-19: "Skills in the char
        // menu, when you click on it, nothing happens" -- SkillsRow above
        // carried no onClick and there was no pane for it to open). Same
        // row+panel+close shape Spells and Pack already use, but read-only:
        // no per-entry Button, see CharacterDossierController.DeclareSkills.
        public NodeRef SkillsChevron;
        public NodeRef SkillsPanel;
        public NodeRef SkillsCloseButton;
        public NodeRef SkillsEmptyHint;
        public List<NodeRef> SkillNames = new List<NodeRef>();
        public List<NodeRef> SkillDescriptions = new List<NodeRef>();

        // The spell-books panel (docs/PLAN_SHOP.md §1g, gate 3): a fourth
        // nav row and a fourth column-A overlay, same shape as Pack's own
        // row+panel pair.
        public NodeRef SpellsRow;
        public NodeRef SpellsChevron;
        public NodeRef SpellsCount;
        public NodeRef SpellsPanel;
        public NodeRef SpellsCloseButton;
        public List<NodeRef> SpellSlots = new List<NodeRef>();
        public List<NodeRef> SpellSlotNames = new List<NodeRef>();
        public List<NodeRef> SpellSlotSelections = new List<NodeRef>();
        public List<NodeRef> SpellSlotIcons = new List<NodeRef>();

        // Stands in the band the three slots occupy, for a character whose
        // pool refuses books. Exactly one of the two is ever on screen; see
        // BuildSpellsPanel.
        public NodeRef SpellsNoBooksLine;

        public NodeRef UnassignedEmptyHint;
        public List<NodeRef> UnassignedRows = new List<NodeRef>();
        public List<NodeRef> UnassignedNames = new List<NodeRef>();
        public List<NodeRef> UnassignedIcons = new List<NodeRef>();
        public List<NodeRef> UnassignedSelections = new List<NodeRef>();

        public NodeRef PackPanel;
        public NodeRef PackCloseButton;
        public List<NodeRef> PackFilterTabs = new List<NodeRef>();
        public List<NodeRef> PackCells = new List<NodeRef>();
        public List<NodeRef> PackIcons = new List<NodeRef>();
        public List<NodeRef> PackCounts = new List<NodeRef>();
        public List<NodeRef> PackRarityTicks = new List<NodeRef>();

        // NO PER-CELL FOCUS HALOS ON THIS SCREEN ANY MORE. Three groups
        // carried one each (the pack cells here, the paperdoll's slots, the
        // ability-score cells) -- AUDIT.md #160's answer to "a NoChrome cell
        // answers gamepad focus with nothing at all". It was the right
        // problem and the wrong shape: the owner played it on a pad and
        // reported "a player can't see where they're going in the character
        // sheets screen: no obvious selectors", because a soft radial glow
        // the same footprint as a cell, over an icon and a name, is not a
        // selector -- it is a tint. Core/FocusMarker.cs's arrow is, and it is
        // the same arrow on every screen.

        // ITEM-MODIFIER PLAN PHASE E: the RiftTier ring, inset within the
        // icon's own bounds (see BuildPack's own comment on why) rather than
        // bleeding past the cell the way the Reckoning's halo/burst do --
        // the pack cell has almost no padding left to bleed into.
        public List<NodeRef> PackRiftGlows = new List<NodeRef>();

        // The name beside each icon, which two-abreast rows have room for and
        // a four-across grid of squares did not.
        public List<NodeRef> PackNames = new List<NodeRef>();

        // Underlines, one per sort key, showing which ordering is live -- the
        // same marker the system menu's tab bar uses, for the same reason.
        public List<NodeRef> PackSortUnderlines = new List<NodeRef>();

        public NodeRef PackScrollTrack;
        public NodeRef PackScrollThumb;
        public NodeRef CarriedValue;

        // Indexed by EquipmentSlots.All.
        public List<NodeRef> SlotCells = new List<NodeRef>();
        public List<NodeRef> SlotIcons = new List<NodeRef>();
        public List<NodeRef> SlotLabels = new List<NodeRef>();
        public List<NodeRef> SlotRarityTicks = new List<NodeRef>();

        // ITEM-MODIFIER PLAN PHASE E: see PackRiftGlows' own comment.
        public List<NodeRef> SlotRiftGlows = new List<NodeRef>();
        public List<NodeRef> SlotBlockedCaptions = new List<NodeRef>();

        // Six cells, filled highest-first at runtime -- which attribute lands
        // in which cell is a per-character question, so the nodes stay generic.
        public List<NodeRef> AttributeCells = new List<NodeRef>();
        public List<NodeRef> AttributeValues = new List<NodeRef>();
        public List<NodeRef> AttributeKeys = new List<NodeRef>();
        public List<NodeRef> AttributePluses = new List<NodeRef>();
        public List<NodeRef> AttributeMinuses = new List<NodeRef>();
        public NodeRef UnspentPoints;

        // The compact grid's own opener -- see BuildColumnC's own comment.
        public NodeRef AttributesRow;

        // The attributes panel (owner item: "dedicated attributes screen
        // showing stat effects, with mouse/gamepad allocation and
        // reallocation"). A fifth Ui.Modal-covered state, same
        // row+panel+close shape Pack/Spells/Skills/Track already use, except
        // this one covers the WHOLE dossier rather than column A alone --
        // its content (six rows of numbers AND prose) does not fit column
        // C's 400px, and a modal already dims/blocks everything behind it by
        // definition (Ui.Modal's own header), so there is nothing column A
        // or B could still usefully show while it is open.
        //
        // Rows are in EXACTLY _cellOrder's order (CharacterDossierController
        // -- dominant score first), the same order the compact grid above
        // already uses, so a row's index means the same score in both
        // places and Spend(int)/Refund(int) need no second overload.
        public NodeRef AttributesPanel;
        public NodeRef AttributesCloseButton;
        public NodeRef AttributesUnspentPoints;

        // Shown only while a run is in progress -- the same refund lock
        // CharacterDossierController.Refund already enforces
        // (lockedForFight || InDescent). Inactive otherwise.
        public NodeRef AttributesLockNote;

        // One row per ability score. AttributeRowSteps is the row itself --
        // a plain Panel at build time, promoted to a Button-derived
        // AttributeRow component in ScreenRegistry.WireDossier (the exact
        // shape OptionRow/ScreenRegistry.WireOptions already uses for a
        // Left/Right-adjustable row) so a focused row answers Left/Right as
        // refund/spend and Submit as spend, matching
        // Core/OptionsController's stepper rows without copying that class.
        public List<NodeRef> AttributeRowSteps = new List<NodeRef>();

        // ONE LINE, not two -- the score and its invested count are folded
        // into this same label ("STR 18 - 4 invested", PaintAttributesPanel)
        // rather than a second column fighting AttributeRowEffects for the
        // same row width.
        public List<NodeRef> AttributeRowNames = new List<NodeRef>();
        public List<NodeRef> AttributeRowEffects = new List<NodeRef>();
        public List<NodeRef> AttributeRowPluses = new List<NodeRef>();
        public List<NodeRef> AttributeRowMinuses = new List<NodeRef>();

        // Indexed by SheetStats.Derived.
        public List<NodeRef> StatNames = new List<NodeRef>();
        public List<NodeRef> StatValues = new List<NodeRef>();
        public List<NodeRef> StatPreviews = new List<NodeRef>();
        public List<NodeRef> StatHighlights = new List<NodeRef>();

        public NodeRef Tooltip;
        public NodeRef TooltipTitle;
        public NodeRef TooltipBody;

        public static CharacterDossierScreen Build()
        {
            var screen = new CharacterDossierScreen();

            // The stat list is generated from SheetStats, so it can outgrow its
            // column the moment somebody adds a row. Same guard, same reasoning
            // as the system menu's tab bar.
            int statCount = SheetStats.Derived.Length;
            if (!DossierLayout.StatListFits(statCount))
            {
                throw new System.InvalidOperationException(
                    $"The dossier has {statCount} stat rows but column C holds {DossierLayout.MaxStatRows()} " +
                    $"at {DossierLayout.StatRowHeight}px. Shorten the rows, lengthen the panel, or the list " +
                    "needs to scroll - it cannot simply be given another entry.");
            }

            var children = new List<UiNode>();

            // ITS OWN GROUND, restored -- the same flat #120a18 fill this pane
            // drew before 2f3ccd0's container, back again since the outer
            // Blue 2:1 frame that replaced it is gone (balance-bot item 2,
            // 2026-09-03). This pane opens over the hub and the fight, and a
            // transparent sheet lets a painted background read straight
            // through the numerals. The DossierVeil "light from above" wash
            // is NOT reinstated with it -- it was a hierarchy fix for a flat
            // field of equal-weight columns, and column A's own Blue 3:4 card
            // already gives this pane the hierarchy it needs.
            children.Add(Ui.Solid("DossierGround", Ground,
                    new UiVec(DossierLayout.Width, DossierLayout.Height), Place.At(0f, 0f))
                .AsDecor());

            children.Add(screen.BuildColumnAFrame());
            children.AddRange(screen.BuildColumnB());
            children.AddRange(screen.BuildColumnC());

            // The two column dividers, sized to the outer container's own
            // content extent (HalfHeight * 2f) rather than the raw 804-tall
            // frame -- Height would now run past the painted border.
            float dividerHeight = DossierLayout.HalfHeight * 2f - DossierLayout.PadY * 2f;
            children.Add(Ui.Solid("DossierDividerAB", Rule,
                new UiVec(1f, dividerHeight),
                Place.At(DossierLayout.DividerAtoB, 0f)).AsDecor());
            children.Add(Ui.Solid("DossierDividerBC", Rule,
                new UiVec(1f, dividerHeight),
                Place.At(DossierLayout.DividerBtoC, 0f)).AsDecor());

            // The pack covers column A entirely, so it is declared AFTER it.
            children.Add(screen.BuildPackPanel());

            // Same shape, one row later: covers column A too, and is
            // declared after the pack so the two never fight over which one
            // draws on top (only one is ever active at a time, per the
            // controller's own arm-one-panel-at-a-time rule).
            children.Add(screen.BuildSpellsPanel());

            // Same shape again, one row later still: covers column A too,
            // and declared after both so the three can never fight over
            // which one draws on top (only one is ever active, per the
            // controller's own arm-one-panel-at-a-time rule).
            children.Add(screen.BuildSkillsPanel());

            // And the tooltip over everything -- except the attributes
            // panel, declared after it below, which is a MODAL and has to
            // sit over the tooltip too (it dims and blocks the whole screen
            // by definition; the controller also closes any open tooltip
            // the moment it opens, so the two are never live at once, but
            // draw order still has to agree with that intent).
            children.Add(screen.BuildTooltip());

            // THE ATTRIBUTES PANEL, last, so it covers everything above --
            // see AttributesPanel's own comment for why this one dims the
            // whole dossier rather than only column A the way Pack/Spells/
            // Skills/Track do.
            children.Add(screen.BuildAttributesPanel());

            // NO OUTER FRAME (balance-bot item 2, 2026-09-03) -- the Blue 2:1
            // container 2f3ccd0 wrapped this pane in was "the big blue
            // container": a second frame around column A's own Blue 3:4
            // card, reading as one frame nested in another rather than one
            // clear card. Column A keeps its card; this pane goes back to a
            // bare panel the size of the content area, same as before that
            // commit and same as the flat ground it briefly replaced (no veil
            // reinstated either -- the system menu's own pane background
            // already grounds this, which is what let the veil be dropped
            // for the container's border in the first place).
            var pane = Ui.Panel("CharacterDossier", Place.At(0f, 0f),
                UiSize.Fixed(DossierLayout.Width, DossierLayout.Height), children.ToArray());

            screen.Root = pane;
            return screen;
        }

        // ---- column A: identity ---------------------------------------------------

        // GRAPHIC-LESS since 2026-09-07 (owner's call: every kit frame inside
        // the system menu read as ugly). Column A kept a Blue 3:4 Container
        // here until then; the RECT survives at the exact same size and place
        // -- DossierLayout.ColumnAFrameHeight still derives from the 3:4
        // aspect it was authored to fill, ColumnATop/ColumnABottom still
        // measure against it -- only the painted border and the separate
        // inset content panel are gone. The identity content (portrait, name,
        // pager, XP, nav rows) is a direct child of this one panel now, at
        // cx = 0 (column A's own centre, not the dossier's), the same
        // convention BuildPackPanel already uses for content that lives on a
        // panel placed at ColumnACentreX. CharacterDossierScreenTests.
        // ColumnAIdentityContentRidesInsideTheFrame pins that the identity
        // content still rides inside this one named parent, so moving or
        // hiding it cannot strand a label over the sky beside it.
        private UiNode BuildColumnAFrame()
        {
            return Ui.Panel("DossierColumnAFrame",
                Place.At(DossierLayout.ColumnACentreX, 0f),
                UiSize.Fixed(DossierLayout.ColumnAWidth, DossierLayout.ColumnAFrameHeight),
                BuildColumnA().ToArray());
        }

        private IEnumerable<UiNode> BuildColumnA()
        {
            const float cx = 0f;

            var portrait = Ui.Sprite("DossierPortrait", PortraitKey,
                    Place.At(cx, DossierLayout.PortraitCentreY),
                    UiSize.Fixed(DossierLayout.ContentAWidth, DossierLayout.PortraitHeight))
                .Coloured("#6640884D")
                .AsDecor();
            Portrait = portrait;
            yield return portrait;

            var name = Ui.Label("DossierName", UiString.Runtime,
                new UiVec(DossierLayout.ContentAWidth - 76f, 42f), 34, TextHi,
                Place.At(cx, DossierLayout.NameCentreY));
            CharacterName = name;
            yield return name;

            // The roster arrows the old sheet had. The handover does not show
            // them -- it draws one character -- but the game has five and no
            // other way to reach them from here, so dropping them would be a
            // capability regression dressed as a redesign.
            var pager = Ui.Pager(
                "DossierPrevCharacter",
                Place.At(cx - DossierLayout.ContentAWidth * 0.5f + 17f, DossierLayout.NameCentreY),
                "DossierNextCharacter",
                Place.At(cx + DossierLayout.ContentAWidth * 0.5f - 17f, DossierLayout.NameCentreY),
                new UiVec(34f, 34f), 18);
            PrevCharacterButton = pager.Prev;
            NextCharacterButton = pager.Next;
            yield return pager.Prev;
            yield return pager.Next;

            var sub = Ui.Label("DossierSubLine", UiString.Runtime,
                new UiVec(DossierLayout.ContentAWidth, 24f), 14, Accent,
                Place.At(cx, DossierLayout.SubLineCentreY));
            SubLine = sub;
            yield return sub;

            // XP: label, a 3px track with its fill, and what is left.
            yield return Ui.Label("DossierXpLabel", UiStrings.OverlayXp, new UiVec(30f, 16f), 10, TextDim,
                Place.At(cx - DossierLayout.ContentAWidth * 0.5f + 15f, DossierLayout.XpRowCentreY)).AsDecor();

            float trackWidth = DossierLayout.XpTrackWidth;
            float trackLeft = cx + DossierLayout.XpTrackLeft;
            yield return Ui.Solid("DossierXpTrack", "#C8B4DE24",
                new UiVec(trackWidth, 3f),
                Place.At(trackLeft + trackWidth * 0.5f, DossierLayout.XpRowCentreY)).AsDecor();

            var fill = Ui.Solid("DossierXpFill", Accent, new UiVec(trackWidth, 3f),
                    Place.At(trackLeft, DossierLayout.XpRowCentreY, new UiVec(0f, 0.5f)))
                .AsDecor();
            XpFill = fill;
            yield return fill;

            var left = Ui.Label("DossierXpRemaining", UiString.Runtime, new UiVec(70f, 16f), 11, TextDim,
                Place.At(cx + DossierLayout.ContentAWidth * 0.5f - 35f, DossierLayout.XpRowCentreY));
            XpRemaining = left;

            yield return left;

            // The two nav rows. BuildNavRow assigns its own refs -- an iterator
            // cannot carry `out` parameters, and threading them back through the
            // caller bought nothing.
            yield return BuildNavRow("Spells", UiStrings.DossierSpellsRow, DossierLayout.SpellsNavRowCentreY);
            yield return BuildNavRow("Track", UiStrings.TrackRow, DossierLayout.TrackNavRowCentreY);
            yield return BuildNavRow("Skills", UiStrings.OverlaySkills, DossierLayout.SkillsRowCentreY);
            yield return BuildNavRow("Pack", UiStrings.OverlayPack, DossierLayout.PackRowCentreY);
        }

        // LEFT AS THE HAIRLINE LIST THEY ARE (owner's HQ-kit instruction,
        // 2026-09-07, with the checked-and-declined exception the
        // instruction itself allows for). 380x56 rows are 6.79:1, nearest
        // Row6x1's 6:1 -- but the honest resize is 380x63.3, and stacking
        // four of those (NavRowHeight applied four times from
        // ColumnABottom) pushes the topmost row's (Spells) top edge to
        // roughly y=-10.1, thirteen pixels ABOVE the reward-track readout's
        // own bottom edge at roughly y=-23.4 (DossierLayout.TrackRowCentreY
        // minus half TrackRowHeight) -- a real overlap under the XP bar, not
        // a near miss, and one that does not depend on canvas aspect since
        // nothing in this column's arithmetic reads one. Growing the rows
        // would mean shrinking something above them (the portrait already
        // absorbed 165px of a prior repin, per DossierLayout.PortraitHeight's
        // own comment) rather than a free resize, so this is left as it was.
        private UiNode BuildNavRow(string key, UiString label, float centreY)
        {
            const float cx = 0f;

            var button = Ui.Button($"Dossier{key}Row", UiString.Runtime,
                    new UiVec(DossierLayout.ContentAWidth, DossierLayout.NavRowHeight), 1,
                    Place.At(cx, centreY))
                .NoChrome();

            button.Children.Add(Ui.Solid($"Dossier{key}RowRule", Rule,
                new UiVec(DossierLayout.ContentAWidth, 1f),
                Place.At(0f, DossierLayout.NavRowHeight * 0.5f - 0.5f)).AsDecor());

            // ...RowName, NOT ...RowLabel. UiEmitter names a button's own
            // caption "<button>Label", so a child called that collides with an
            // object the tree never declares and every lookup by name silently
            // takes the emitter's empty one -- AUDIT #39, caught here by the
            // check that finding added.
            button.Children.Add(Ui.Label($"Dossier{key}RowName", label,
                new UiVec(160f, 24f), 17, Text,
                Place.At(-DossierLayout.ContentAWidth * 0.5f + 82f, 0f)).AsDecor());

            // WIDER FOR THE TRACK. "LEVEL 6: +3% EXPERIENCE" does not fit the
            // 90px a count like "0 known" needs, and shrinking it to fit would
            // make the one sentence on this screen that names a reward the
            // smallest text on it.
            float countWidth = key == "Track" ? 210f : 90f;
            var countLabel = Ui.Label($"Dossier{key}RowCount", UiString.Runtime,
                new UiVec(countWidth, 20f), key == "Track" ? 11 : 12, TextDim,
                Place.At(DossierLayout.ContentAWidth * 0.5f - 6f - countWidth * 0.5f, 0f)).AsDecor();
            button.Children.Add(countLabel);

            var chev = Ui.Label($"Dossier{key}RowChevron", UiString.Runtime,
                new UiVec(20f, 24f), 16, Accent,
                Place.At(DossierLayout.ContentAWidth * 0.5f - 12f, 0f)).AsDecor();
            button.Children.Add(chev);

            // Assigned here rather than returned, so the two call sites stay
            // one line each.
            // The track row's COUNT LABEL is where "LEVEL 6: +3% EXPERIENCE"
            // now lives. It was a standalone line under the XP bar until this
            // screen existed -- two readouts of one fact, and UiAudit caught
            // them overlapping the moment the row arrived. The row is the
            // better home: it says what is next AND is the door to the rest.
            if (key == "Skills") { SkillsRow = button; SkillsCount = countLabel; SkillsChevron = chev; }
            else if (key == "Track") { TrackRow = button; TrackNext = countLabel; }
            else if (key == "Spells") { SpellsRow = button; SpellsCount = countLabel; SpellsChevron = chev; }
            else { PackRow = button; PackChevron = chev; }

            return button;
        }

        // ---- column A, covered: the pack -------------------------------------------

        private static UiString SortLabel(BagSortKey key)
        {
            switch (key)
            {
                case BagSortKey.Plus: return UiStrings.PackSortPlus;
                case BagSortKey.Name: return UiStrings.PackSortName;
                default: return UiStrings.PackSortTier;
            }
        }

        private UiNode BuildPackPanel()
        {
            // ZERO, not the column centre. These are children OF the pack
            // panel, and the panel is itself placed at column A -- expressing
            // them in dossier coordinates offset every one of them twice, which
            // the child-containment audit caught as a 339px escape rather than
            // letting it ship as a pack drawn off the side of the screen.
            const float cx = 0f;
            var children = new List<UiNode>();

            children.Add(Ui.Label("DossierPackTitle", UiStrings.OverlayPackTitle,
                new UiVec(170f, 22f), 13, TextFaint,
                Place.At(cx - DossierLayout.ContentAWidth * 0.5f + 75f, DossierLayout.ColumnATop - 10f)).AsDecor());

            // SILVER THEMED PLATE, small, at nominal aspect (owner's HQ-kit
            // instruction, 2026-09-07) -- the flat NoChrome box this drew was
            // 110x28 (3.93:1), past every plate shape's own tolerance
            // (ThemedButtonAspectLintTests). HEIGHT kept, not width, this
            // time -- Ui.PlateNominalSizeFor's own width-fixed shrink (110
            // wide -> 22 tall) cleared the lint but left "CLOSE" at font
            // size 15 needing 81.1x27.9, which a 22-tall box cannot hold
            // (UiTextFitAudit, a scene-build check the dotnet lint suite
            // does not run). FiveByOne at the UNCHANGED 28 tall resolves to
            // 140 wide instead -- same shape ShapeFor already picks for
            // this aspect, solved for the axis that was already proven to
            // fit the caption. Right-aligned off its own half-width now
            // rather than the old literal 55, so a caller changing this
            // size again cannot silently misalign it against the column's
            // right edge the way a stale literal would.
            var closeShape = Ui.PlateShapeFor(110f, 28f);
            var closeSize = new UiVec(28f * Ui.PlateAspect(closeShape), 28f);
            var close = Ui.Button("DossierPackClose", UiStrings.OverlayPackClose, closeSize, 15,
                    Place.At(cx + DossierLayout.ContentAWidth * 0.5f - closeSize.X * 0.5f,
                             DossierLayout.ColumnATop - 12f))
                .Themed(ButtonTheme.Silver);
            PackCloseButton = close;
            children.Add(close);

            children.Add(Ui.Solid("DossierPackHeaderRule", Rule,
                new UiVec(DossierLayout.ContentAWidth, 1f),
                Place.At(cx, DossierLayout.ColumnATop - 26f)).AsDecor());

            // HOW THE PACK IS ORDERED, chosen by the player.
            //
            // Three keys, not the four that were asked for: rarity is derived
            // from tier by RarityBands, so a rarity button would produce the
            // tier button's list with the precision thrown away. Two controls
            // that do the same thing is the same failure as one that does
            // nothing. See BagSort.
            for (int i = 0; i < BagSort.All.Length; i++)
            {
                float x = cx - DossierLayout.ContentAWidth * 0.5f
                          + DossierLayout.PackSortButtonWidth * (i + 0.5f);

                // SILVER THEMED PLATE, like GlossaryScreen.BuildCategory's own
                // rail tabs (owner's HQ-kit instruction, 2026-09-07) -- the
                // flat NoChrome box this drew was 84x32 (2.625:1), past
                // Legacy's own tolerance (ThemedButtonAspectLintTests).
                // Width kept, height down to Legacy's honest 28.
                // ThemedPlate, not Themed(), because a hand-declared Caption
                // is what GlossaryScreen's own comment recommends for a row
                // that would otherwise fight a generated <button>Label for
                // the same box -- here there is no generated label to fight,
                // but the shape is copied for consistency with the rest of
                // this pass. The sort's selected state stays exactly what it
                // was: PackSortUnderlines below, driven by
                // CharacterDossierController.RefreshSortMarkers -- this
                // change touches only the plate, not that seam.
                var label = SortLabel(BagSort.All[i]);
                var tabSize = Ui.PlateNominalSizeFor(
                    DossierLayout.PackSortButtonWidth, DossierLayout.PackSortRowHeight);
                var tab = Ui.Button($"DossierPackSort{i}", label, tabSize, 14,
                        Place.At(x, DossierLayout.PackSortCentreY))
                    .ThemedPlate(ButtonTheme.Silver);

                // Caption, NOT Label -- UiEmitter names a button's own
                // generated text "<button>Label", and ThemedPlate's
                // CaptionPreserving generates none at all, so this is the
                // tab's only caption and nothing can collide with it.
                var caption = Ui.Label($"DossierPackSort{i}Caption", label,
                        new UiVec(tabSize.X - 10f, 20f), 14, Text, Place.At(0f, 0f))
                    .AsDecor();
                tab.Children.Add(caption);
                tab.LayerCaptionWithVisuals(caption);

                var underline = Ui.Solid($"DossierPackSort{i}Underline", "#FFE0A8",
                        new UiVec(DossierLayout.PackSortButtonWidth - 24f, 2f),
                        Place.At(x, DossierLayout.PackSortCentreY - DossierLayout.PackSortRowHeight * 0.5f + 1f))
                    .Inactive()
                    .AsDecor();

                PackFilterTabs.Add(tab);
                PackSortUnderlines.Add(underline);
                children.Add(tab);
                children.Add(underline);
            }

            // TWO ABREAST, AND ONLY WHAT FITS. The cells are a WINDOW onto the
            // bag rather than its capacity: the controller binds cell i to item
            // i + offset, so a pack of any size is reachable by scrolling and a
            // 25th item is no longer simply absent.
            float cellW = DossierLayout.PackCellWidth;
            float cellH = DossierLayout.PackCellHeight;

            for (int i = 0; i < DossierLayout.PackVisibleCells; i++)
            {
                int col = i % (int)DossierLayout.PackColumns;
                int rowIndex = i / (int)DossierLayout.PackColumns;

                float x = cx + DossierLayout.PackCellCentreX(col);
                float y = DossierLayout.PackCellCentreY(rowIndex);

                // CENTRED AND ON TOP. Half again the size it was, because the
                // icon is what the eye actually sorts by.
                var icon = Ui.Sprite($"DossierPackIcon{i}", null,
                        new UiVec(DossierLayout.PackIconSize, DossierLayout.PackIconSize),
                        Place.At(0f, DossierLayout.PackIconCentreY))
                    .Inactive().AsDecor();

                var tick = Ui.Solid($"DossierPackTick{i}", "#7F8EA3", new UiVec(12f, 12f),
                    Place.At(-cellW * 0.5f + 9f, cellH * 0.5f - 9f)).Inactive().AsDecor();

                // ITEM-MODIFIER PLAN PHASE E: the RiftTier ring. Sized to the
                // ICON itself (not larger) and centred on it -- proc:ring_
                // hairline draws its stroke well inside its own bounds (see
                // ProceduralSpriteBaker's own Radius 0.94), so this reads as
                // a thin coloured frame around the art without needing an
                // AllowOverflow the way the Reckoning's bleeding halo does:
                // PackIconSize already spends nearly the whole cell width
                // (PackIconPadX is 4px), so there is no room to bleed into.
                // Coloured and shown at runtime by
                // CharacterDossierController.BindPackWindow; inactive here
                // the same way every other per-item decoration in this loop
                // starts, so an empty window slot draws nothing.
                var riftGlow = Ui.Sprite($"DossierPackRiftGlow{i}", "proc:ring_hairline",
                        new UiVec(DossierLayout.PackIconSize, DossierLayout.PackIconSize),
                        Place.At(0f, DossierLayout.PackIconCentreY))
                    .Inactive().AsDecor();

                // UNDER the icon and the full width of the cell, which is the
                // whole point of the change: beside a 44px icon this had about
                // 110px, and a generated item's name does not fit in 110px at a
                // size anyone can read.
                // 15px, up from 11. The cell is twice the height it was and the
                // name owns the surplus, so the old size left it small text
                // floating in a large box -- which reads as worse, not better.
                var name = Ui.Label($"DossierPackName{i}", UiString.Runtime,
                        new UiVec(cellW - 12f, DossierLayout.PackNameHeight), 15, Text,
                        Place.At(0f, DossierLayout.PackNameCentreY))
                    .Inactive().AsDecor();

                // TOP right, not bottom: the name owns the bottom of the cell
                // now, and a count sitting in it would print across the words.
                var count = Ui.Label($"DossierPackCount{i}", UiString.Runtime, new UiVec(34f, 18f), 13,
                    "#E6DCF0BF", Place.At(cellW * 0.5f - 19f, cellH * 0.5f - 12f)).Inactive().AsDecor();

                var button = Ui.Button($"DossierPackCell{i}", UiString.Runtime, new UiVec(cellW, cellH), 1,
                        Place.At(x, y))
                    .NoChrome()
                    .Hovers(1.02f)
                    .AllowOverlap("an entry's icon, name and count sit inside their own row by construction");

                button.Children.Add(icon);
                button.Children.Add(riftGlow);
                button.Children.Add(tick);
                button.Children.Add(name);
                button.Children.Add(count);

                PackCells.Add(button);
                PackIcons.Add(icon);
                PackRiftGlows.Add(riftGlow);
                PackRarityTicks.Add(tick);
                PackNames.Add(name);
                PackCounts.Add(count);
                children.Add(button);
            }

            // The scrollbar. A track and a thumb the controller sizes and
            // moves, rather than a ScrollRect: there is no scrolling CONTENT
            // here to move -- the cells stay put and their CONTENTS change --
            // so a real viewport would be machinery around a list that does not
            // need one.
            var track = Ui.Solid("DossierPackScrollTrack", "#0E070CD9",
                    new UiVec(DossierLayout.PackScrollbarWidth, DossierLayout.PackTrackHeight),
                    Place.At(cx + DossierLayout.PackScrollbarCentreX, DossierLayout.PackTrackCentreY));

            var thumb = Ui.Solid("DossierPackScrollThumb", "#C8AAE666",
                    new UiVec(DossierLayout.PackScrollbarWidth, DossierLayout.PackTrackHeight),
                    Place.At(cx + DossierLayout.PackScrollbarCentreX, DossierLayout.PackTrackCentreY))
                .AsDecor();

            PackScrollTrack = track;
            PackScrollThumb = thumb;
            children.Add(track);
            children.Add(thumb);

            float footerY = -DossierLayout.HalfHeight + DossierLayout.PadY + 16f;
            children.Add(Ui.Solid("DossierPackFooterRule", Rule,
                new UiVec(DossierLayout.ContentAWidth, 1f), Place.At(cx, footerY + 18f)).AsDecor());
            children.Add(Ui.Label("DossierCarriedLabel", UiStrings.OverlayCarried, new UiVec(110f, 20f), 13,
                TextDim, Place.At(cx - DossierLayout.ContentAWidth * 0.5f + 55f, footerY)).AsDecor());

            var carried = Ui.Label("DossierCarriedValue", UiString.Runtime, new UiVec(110f, 20f), 14, Text,
                Place.At(cx + DossierLayout.ContentAWidth * 0.5f - 55f, footerY));
            CarriedValue = carried;
            children.Add(carried);

            // The PANEL sits over column A; its CHILDREN are relative to the
            // panel, hence cx = 0 above. Collapsing both onto one variable put
            // the whole pack in the middle of the screen, over the loadout.
            // Height * 0.5f no longer clears the outer container's own
            // content box (balance-bot, 2026-09-02) -- HalfHeight * 2f is the
            // box this panel is actually a child of now.
            var panel = Ui.Sprite("DossierPackPanel", null,
                    Place.At(DossierLayout.ColumnACentreX, 0f),
                    UiSize.Fixed(DossierLayout.ColumnAWidth, DossierLayout.HalfHeight * 2f))
                .Coloured(PackGround)
                .Inactive()
                .AllowOverlap("the pack covers column A entirely - that IS the interaction");

            foreach (var child in children) panel.Children.Add(child);
            PackPanel = panel;
            return panel;
        }

        public const int PackCapacity = 24;

        // ---- column A, covered: spell books (docs/PLAN_SHOP.md §1g) --------------

        // How many pending books show at once. Not the pool's capacity --
        // same "a window, not the whole thing" posture the pack's own cells
        // take (PackVisibleCells) -- a fixed count emitted at build time.
        // Five is generous against what a single-character-squad run can
        // realistically be carrying unplaced at once; paging is the
        // Pack-style follow-up the day it is not (§2d's own precedent for
        // when to add one: not before there is something to page).
        public const int UnassignedVisibleCount = 5;

        private UiNode BuildSpellsPanel()
        {
            // Zero, not the column centre -- same reason BuildPackPanel's
            // children are cx-relative: this panel is ITSELF placed at
            // column A, so a dossier-space coordinate here would offset
            // twice.
            const float cx = 0f;
            var children = new List<UiNode>();

            children.Add(Ui.Label("DossierSpellsTitle", UiStrings.ShopSectionBooks,
                new UiVec(170f, 22f), 13, TextFaint,
                Place.At(cx - DossierLayout.ContentAWidth * 0.5f + 75f, DossierLayout.ColumnATop - 10f)).AsDecor());

            // SILVER THEMED PLATE, small, at nominal aspect (owner's HQ-kit
            // instruction, 2026-09-07) -- same shape, same height-fixed
            // solve, and same reason as DossierPackClose above (that
            // comment has the UiTextFitAudit numbers this avoids).
            var spellsCloseShape = Ui.PlateShapeFor(110f, 28f);
            var spellsCloseSize = new UiVec(28f * Ui.PlateAspect(spellsCloseShape), 28f);
            var close = Ui.Button("DossierSpellsClose", UiStrings.OverlayPackClose, spellsCloseSize, 15,
                    Place.At(cx + DossierLayout.ContentAWidth * 0.5f - spellsCloseSize.X * 0.5f,
                             DossierLayout.ColumnATop - 12f))
                .Themed(ButtonTheme.Silver);
            SpellsCloseButton = close;
            children.Add(close);

            children.Add(Ui.Solid("DossierSpellsHeaderRule", Rule,
                new UiVec(DossierLayout.ContentAWidth, 1f),
                Place.At(cx, DossierLayout.ColumnATop - 26f)).AsDecor());

            // THREE SLOTS, pinned against SpellBooks.MaxSpellSlots rather
            // than typed here -- a literal 3 is the drift E4's own pairing
            // exists to catch one level up.
            const float slotHeight = 56f;
            const float slotGap = 8f;
            float slotTop = DossierLayout.ColumnATop - 46f;

            for (int i = 0; i < SpellBooks.MaxSpellSlots; i++)
            {
                float y = slotTop - i * (slotHeight + slotGap) - slotHeight * 0.5f;

                // LOCAL to the slot button below (Place.At(0, 0)), not
                // Place.At(cx, y) again -- these are the BUTTON's children,
                // so re-using its own absolute placement here would offset
                // them a second time (the exact bug ShopScreen's own header
                // comment warns against; caught here by the containment
                // audit rather than by remembering the rule).
                var selection = Ui.Solid($"DossierSpellSlot{i}Selection", "#5A3E7A80",
                        new UiVec(DossierLayout.ContentAWidth, slotHeight), Place.At(0f, 0f))
                    .Inactive()
                    .AsDecor();

                // The book's glyph, left-aligned in the slot -- the book art
                // carries the glyph baked in (README/PLAN_SPELL_BOOK_ART.md),
                // so this is the whole icon and needs no separate glyph
                // overlay the way an item slot's riftGlow does. Sized to fit
                // inside the 56px slot with room above/below; the name label
                // below is shifted right by the same margin so the two never
                // really overlap (UiAudit refuses an overlap that is not
                // explicitly AllowOverlap'd on a non-decor pair).
                const float iconSize = 44f;
                const float iconMargin = 8f;
                const float iconGap = 8f;
                float iconX = -DossierLayout.ContentAWidth * 0.5f + iconMargin + iconSize * 0.5f;

                var icon = Ui.Sprite($"DossierSpellSlot{i}Icon", null,
                        new UiVec(iconSize, iconSize), Place.At(iconX, 0f))
                    .Inactive()
                    .AsDecor();

                // Right of the icon, not centred -- the original centred
                // label spanned nearly the full slot width, which the icon
                // now sits under.
                float nameRightEdge = DossierLayout.ContentAWidth * 0.5f - 12f;
                float nameLeftEdge = iconX + iconSize * 0.5f + iconGap;
                float nameWidth = nameRightEdge - nameLeftEdge;
                float nameX = (nameLeftEdge + nameRightEdge) * 0.5f;

                var name = Ui.Label($"DossierSpellSlot{i}Name", UiString.Runtime,
                        new UiVec(nameWidth, 24f), 16, Text,
                        Place.At(nameX, 0f)).AsDecor();

                var slot = Ui.Button($"DossierSpellSlot{i}", UiString.Runtime,
                        new UiVec(DossierLayout.ContentAWidth, slotHeight), 1, Place.At(cx, y))
                    .NoChrome()
                    .AllowOverlap("the selection tint, the icon and the name sit inside their own slot by construction");
                slot.Children.Add(selection);
                slot.Children.Add(icon);
                slot.Children.Add(name);

                SpellSlots.Add(slot);
                SpellSlotSelections.Add(selection);
                SpellSlotIcons.Add(icon);
                SpellSlotNames.Add(name);
                children.Add(slot);
            }

            // WHAT REPLACES THE THREE SLOTS for a character whose primary pool
            // refuses spell books (plan P6, gate 3). Centred in the band they
            // occupy, so the panel's own geometry does not move for either
            // reading -- the divider and everything under it stay where they
            // are whichever of the two is up.
            //
            // DECOR, which is also what exempts it from A1: it overlaps all
            // three slot buttons by construction and CheckSiblingOverlap skips
            // any pair with a decor side, so there is no AllowOverlap to
            // declare here (A7 would refuse one on a decor node as a waiver
            // that waives nothing). Nothing about this line takes a click.
            //
            // The pattern is FightScreen's roster signature row: hidden
            // outright rather than blanked, because a label set to "" is still
            // a box the text-fit audit reasons about and still reads as a
            // missing value rather than as an absence with a reason.
            float slotBandHeight = SpellBooks.MaxSpellSlots * slotHeight + (SpellBooks.MaxSpellSlots - 1) * slotGap;
            var noBooks = Ui.Label("DossierSpellsNoBooksLine", UiStrings.DossierNoSpellBooks,
                    new UiVec(DossierLayout.ContentAWidth, 24f), 14, TextDim,
                    Place.At(cx, slotTop - slotBandHeight * 0.5f))
                .AsDecor()
                .Inactive();
            SpellsNoBooksLine = noBooks;
            children.Add(noBooks);

            float dividerY = slotTop - SpellBooks.MaxSpellSlots * (slotHeight + slotGap);
            children.Add(Ui.Solid("DossierSpellsDivider", Rule,
                new UiVec(DossierLayout.ContentAWidth, 1f), Place.At(cx, dividerY)).AsDecor());

            children.Add(Ui.Label("DossierSpellsUnassignedHeader", UiStrings.DossierUnassignedHeader,
                new UiVec(170f, 20f), 13, TextFaint,
                Place.At(cx - DossierLayout.ContentAWidth * 0.5f + 75f, dividerY - 20f)).AsDecor());

            var empty = Ui.Label("DossierSpellsEmptyHint", UiStrings.DossierUnassignedEmpty,
                    new UiVec(DossierLayout.ContentAWidth, 24f), 14, TextDim, Place.At(cx, dividerY - 60f))
                .AsDecor()
                .Inactive();
            UnassignedEmptyHint = empty;
            children.Add(empty);

            const float rowHeight = 40f;
            const float rowGap = 4f;
            float rowTop = dividerY - 40f;

            for (int i = 0; i < UnassignedVisibleCount; i++)
            {
                float y = rowTop - i * (rowHeight + rowGap) - rowHeight * 0.5f;

                // Local to the row button below, same reason as the slot
                // loop above.
                var selection = Ui.Solid($"DossierUnassigned{i}Selection", "#5A3E7A80",
                        new UiVec(DossierLayout.ContentAWidth, rowHeight), Place.At(0f, 0f))
                    .Inactive()
                    .AsDecor();

                // The book's art, the same 48x48 source the slot above draws,
                // shown at 32 because the row is 40 tall. Same left-aligned
                // icon-then-name shape as the slot, so a book reads as the
                // same object before and after it is placed. Inactive until
                // the controller has a sprite for it (ItemIcons.Apply plus
                // SetShown, the pack cell's pattern): an Image with no sprite
                // is a white quad, not nothing.
                const float rowIconSize = 32f;
                const float rowIconMargin = 8f;
                const float rowIconGap = 8f;
                float rowIconX = -DossierLayout.ContentAWidth * 0.5f + rowIconMargin + rowIconSize * 0.5f;

                var icon = Ui.Sprite($"DossierUnassigned{i}Icon", null,
                        new UiVec(rowIconSize, rowIconSize), Place.At(rowIconX, 0f))
                    .Inactive()
                    .AsDecor();

                // NOT .Inactive(): it used to be, and nothing ever activated
                // it, so every unassigned row was an empty box a player had
                // to click blind. The row itself is what starts hidden.
                float rowNameLeft = rowIconX + rowIconSize * 0.5f + rowIconGap;
                float rowNameRight = DossierLayout.ContentAWidth * 0.5f - 12f;
                var name = Ui.Label($"DossierUnassigned{i}Name", UiString.Runtime,
                        new UiVec(rowNameRight - rowNameLeft, 22f), 15, Text,
                        Place.At((rowNameLeft + rowNameRight) * 0.5f, 0f)).AsDecor();

                var row = Ui.Button($"DossierUnassigned{i}", UiString.Runtime,
                        new UiVec(DossierLayout.ContentAWidth, rowHeight), 1, Place.At(cx, y))
                    .NoChrome()
                    .Inactive()
                    .AllowOverlap("the selection tint, the icon and the name sit inside their own row by construction");
                row.Children.Add(selection);
                row.Children.Add(icon);
                row.Children.Add(name);

                UnassignedRows.Add(row);
                UnassignedSelections.Add(selection);
                UnassignedIcons.Add(icon);
                UnassignedNames.Add(name);
                children.Add(row);
            }

            var panel = Ui.Sprite("DossierSpellsPanel", null,
                    Place.At(DossierLayout.ColumnACentreX, 0f),
                    UiSize.Fixed(DossierLayout.ColumnAWidth, DossierLayout.HalfHeight * 2f))
                .Coloured(PackGround)
                .Inactive()
                .AllowOverlap("this panel covers column A entirely - that IS the interaction, same as the pack");

            foreach (var child in children) panel.Children.Add(child);
            SpellsPanel = panel;
            return panel;
        }

        // ---- column A, covered: skills (owner bug report, 2026-09-19) -------------

        // How many entries show at once. Same "a window, not the whole
        // thing" posture UnassignedVisibleCount above takes, sized against
        // today's content rather than any hard cap: the most any one
        // character's talent tree currently grants is three
        // (talents.json -- Shawn's provoke/black_ram_mode/headbutt), so five
        // is headroom, not a guess.
        public const int SkillsVisibleCount = 5;

        private UiNode BuildSkillsPanel()
        {
            // Zero, not the column centre -- same reason BuildSpellsPanel's
            // children are cx-relative immediately above.
            const float cx = 0f;
            var children = new List<UiNode>();

            children.Add(Ui.Label("DossierSkillsTitle", UiStrings.DossierSkillsTitle,
                new UiVec(170f, 22f), 13, TextFaint,
                Place.At(cx - DossierLayout.ContentAWidth * 0.5f + 75f, DossierLayout.ColumnATop - 10f)).AsDecor());

            // SILVER THEMED PLATE, same shape and same height-fixed solve as
            // DossierSpellsClose/DossierPackClose immediately above -- see
            // DossierPackClose's own comment for the UiTextFitAudit numbers
            // this avoids.
            var closeShape = Ui.PlateShapeFor(110f, 28f);
            var closeSize = new UiVec(28f * Ui.PlateAspect(closeShape), 28f);
            var close = Ui.Button("DossierSkillsClose", UiStrings.OverlayPackClose, closeSize, 15,
                    Place.At(cx + DossierLayout.ContentAWidth * 0.5f - closeSize.X * 0.5f,
                             DossierLayout.ColumnATop - 12f))
                .Themed(ButtonTheme.Silver);
            SkillsCloseButton = close;
            children.Add(close);

            children.Add(Ui.Solid("DossierSkillsHeaderRule", Rule,
                new UiVec(DossierLayout.ContentAWidth, 1f),
                Place.At(cx, DossierLayout.ColumnATop - 26f)).AsDecor());

            // ONE ENTRY, TWO LINES: name, then its description/effect text
            // straight off content (ResolvedSkill.Description -- the same
            // field GlossaryEntries and the shop already show for a skill,
            // so this reads the way the player has already seen a skill
            // described elsewhere). NO BUTTON PER ROW -- unlike a pack cell
            // or an unassigned book, nothing here is placed or equipped;
            // wrapping this in a Selectable with no onClick would be the
            // exact bug this whole panel exists to fix, one level further
            // in. See CharacterDossierController.DeclareSkills.
            const float rowHeight = 76f;
            const float rowGap = 8f;
            const float nameHeight = 20f;
            const float descHeight = 40f;
            const float lineGap = 4f;
            float rowTop = DossierLayout.ColumnATop - 46f;
            float textWidth = DossierLayout.ContentAWidth - 24f;

            for (int i = 0; i < SkillsVisibleCount; i++)
            {
                float top = rowTop - i * (rowHeight + rowGap);
                float nameY = top - nameHeight * 0.5f;
                float descY = nameY - nameHeight * 0.5f - lineGap - descHeight * 0.5f;

                var name = Ui.Label($"DossierSkill{i}Name", UiString.Runtime,
                        new UiVec(textWidth, nameHeight), 16, Text, Place.At(cx, nameY))
                    .Inactive().AsDecor()
                    .TextAligned(UiTextAlign.TopLeft);

                var description = Ui.Label($"DossierSkill{i}Description", UiString.Runtime,
                        new UiVec(textWidth, descHeight), 12, TextDim, Place.At(cx, descY))
                    .Inactive().AsDecor()
                    .TextAligned(UiTextAlign.TopLeft);

                SkillNames.Add(name);
                SkillDescriptions.Add(description);
                children.Add(name);
                children.Add(description);
            }

            // WHAT SHOWS INSTEAD OF THE LIST for a character with no
            // talent-granted skills yet -- same "one sentence, not empty
            // boxes" posture SpellsNoBooksLine/UnassignedEmptyHint already
            // take on this same column. Centred on the whole band the rows
            // above occupy, so the panel's own geometry does not move for
            // either reading.
            float bandHeight = SkillsVisibleCount * rowHeight + (SkillsVisibleCount - 1) * rowGap;
            var empty = Ui.Label("DossierSkillsEmptyHint", UiStrings.DossierSkillsEmpty,
                    new UiVec(DossierLayout.ContentAWidth, 24f), 14, TextDim,
                    Place.At(cx, rowTop - bandHeight * 0.5f))
                .AsDecor()
                .Inactive();
            SkillsEmptyHint = empty;
            children.Add(empty);

            var panel = Ui.Sprite("DossierSkillsPanel", null,
                    Place.At(DossierLayout.ColumnACentreX, 0f),
                    UiSize.Fixed(DossierLayout.ColumnAWidth, DossierLayout.HalfHeight * 2f))
                .Coloured(PackGround)
                .Inactive()
                .AllowOverlap("this panel covers column A entirely - that IS the interaction, same as pack/spells");

            foreach (var child in children) panel.Children.Add(child);
            SkillsPanel = panel;
            return panel;
        }

        // ---- column B: the loadout --------------------------------------------------

        private IEnumerable<UiNode> BuildColumnB()
        {
            yield return Ui.Label("DossierLoadoutLabel", UiStrings.OverlayLoadout,
                new UiVec(160f, 20f), 10, TextFaint,
                Place.At(DossierLayout.ColumnBCentreX - DossierLayout.StageWidth * 0.5f + 80f,
                         DossierLayout.HalfHeight - DossierLayout.PadY - 10f)).AsDecor();

            var mannequinAt = DossierLayout.FromStage(DossierLayout.MannequinLeft, DossierLayout.MannequinTop,
                DossierLayout.MannequinWidth, DossierLayout.MannequinHeight);

            // TWO LAYERS, and the split is the whole point.
            //
            // One solid shape at one opacity cannot do both jobs: raise it far
            // enough to define an edge and it becomes a purple slab competing
            // with the item art hung on it; drop it far enough to recede and
            // the figure stops existing. So the fill carries mass at almost
            // nothing, and a traced line carries the reading. That is also the
            // order the eye wants -- the equipment is the subject here and the
            // body is the armature it hangs from.
            yield return Ui.Sprite("DossierMannequinFill", MannequinKey,
                    Place.At(mannequinAt.X, mannequinAt.Y),
                    UiSize.Fixed(DossierLayout.MannequinWidth, DossierLayout.MannequinHeight))
                .Coloured("#B9A2D60E")
                .AsDecor();

            yield return Ui.Sprite("DossierMannequinOutline", MannequinOutlineKey,
                    Place.At(mannequinAt.X, mannequinAt.Y),
                    UiSize.Fixed(DossierLayout.MannequinWidth, DossierLayout.MannequinHeight))
                .Coloured("#EDE4FF5C")
                .AsDecor();

            foreach (var slot in EquipmentSlots.All)
            {
                foreach (var node in BuildSlot(slot)) yield return node;
            }
        }

        private IEnumerable<UiNode> BuildSlot(EquipmentSlot slot)
        {
            string key = EquipmentSlots.DisplayName(slot).Replace(" ", "");
            var at = DossierLayout.SlotAt(slot);

            // No hairline for the centred pair -- HEAD sits directly above the
            // figure's head and SHOES directly below its feet, so adjacency
            // already says which body part they belong to. Width 0 is how
            // DossierLayout.LeaderAt says so; emitting it anyway would be a
            // zero-sized graphic, which A6 refuses and is right to.
            var leaderAt = DossierLayout.LeaderAt(slot, out float leaderWidth);
            if (leaderWidth > 0f)
            {
                yield return Ui.Solid($"DossierLeader{key}", "#C8B4DE2E",
                    new UiVec(leaderWidth, 1f), Place.At(leaderAt.X, leaderAt.Y)).AsDecor();
            }

            // 6px of inset, down from 12. The slot box cannot grow -- the
            // figure's slots sit 98 authored units apart and the box plus its
            // caption already spend 88 of that -- so the only room left for the
            // ITEM is the padding inside the box it already has.
            // ABOVE THE CAPTION BAND, not across it. The caption moved inside
            // the socket and the icon filled the whole socket, so an equipped
            // sword was drawn straight through the word naming its slot --
            // "WEA(sword)ON 1". The icon gets the socket minus that band.
            const float CaptionBand = 22f;
            float iconSize = DossierLayout.SlotSize - CaptionBand;
            var icon = Ui.Sprite($"DossierSlotIcon{key}", null,
                new UiVec(iconSize, iconSize),
                Place.At(0f, CaptionBand * 0.5f)).Inactive().AsDecor();

            var tick = Ui.Solid($"DossierSlotTick{key}", "#7F8EA3", new UiVec(11f, 11f),
                Place.At(-DossierLayout.SlotSize * 0.5f + 7f, DossierLayout.SlotSize * 0.5f - 7f))
                .Inactive().AsDecor();

            // ITEM-MODIFIER PLAN PHASE E: see BuildPack's identical comment
            // on why this is sized to the icon rather than bled past it.
            var riftGlow = Ui.Sprite($"DossierSlotRiftGlow{key}", "proc:ring_hairline",
                    new UiVec(iconSize, iconSize),
                    Place.At(0f, CaptionBand * 0.5f))
                .Inactive().AsDecor();

            // The blocked caption. A two-handed weapon must never leave the off
            // hand looking merely empty -- the player has to see WHY.
            var blocked = Ui.Label($"DossierSlotBlocked{key}", UiStrings.OverlayTwoHanded,
                new UiVec(DossierLayout.SlotSize - 8f, 26f), 9, TextDim, Place.At(0f, 0f))
                .Inactive().AsDecor();

            var cell = Ui.Button($"DossierSlot{key}", UiString.Runtime,
                    new UiVec(DossierLayout.SlotSize, DossierLayout.SlotSize), 1,
                    Place.At(at.X, at.Y))
                .NoChrome()
                .Hovers(1.05f)
                .AllowOverlap("a slot stands on the mannequin and its own leader line");
            cell.Children.Add(icon);
            cell.Children.Add(riftGlow);
            cell.Children.Add(tick);
            cell.Children.Add(blocked);

            // THE SOCKET'S OWN FRAME, which the handover specified and nothing
            // ever drew: SlotEmptyBorder and SlotBorder have sat in the token
            // table above, declared and referenced by nothing, since the screen
            // was written.
            //
            // Without it an unequipped slot renders as literally nothing -- the
            // loadout was a column of captions at the panel's edge with a
            // leader stub floating near the figure and empty space between them,
            // which is what "the silhouette still looks very weird" was about.
            // Growing the boxes did not help while they were invisible.
            //
            // Drawn at the empty weight for every slot. Swapping to SlotBorder
            // when something is worn needs the controller to hold four node refs
            // per slot, which is a bigger change than making the socket visible
            // at all -- so SlotBorder stays unused for now, and knowingly.
            foreach (var edge in Ui.Rim($"DossierSlot{key}",
                         new UiVec(DossierLayout.SlotSize, DossierLayout.SlotSize), SlotEmptyBorder))
            {
                cell.Children.Add(edge);
            }

            // INSIDE the socket, along its bottom edge.
            //
            // Under the box it spent vertical room the box needed; beside it,
            // once the boxes moved out to their files, the word ended up an
            // inch from the socket it named with nothing between them. Inside,
            // the socket and its word are one object and the files can sit
            // wherever the figure leaves room.
            var label = Ui.Label($"DossierSlotLabel{key}", UiString.Runtime,
                new UiVec(DossierLayout.SlotSize - 8f, 16f), 11, TextDim,
                Place.At(at.X, at.Y - DossierLayout.SlotSize * 0.5f + 11f)).AsDecor();

            SlotCells.Add(cell);
            SlotIcons.Add(icon);
            SlotRiftGlows.Add(riftGlow);
            SlotRarityTicks.Add(tick);
            SlotBlockedCaptions.Add(blocked);
            SlotLabels.Add(label);

            yield return cell;
            yield return label;
        }

        // ---- column C: the numbers ---------------------------------------------------

        private IEnumerable<UiNode> BuildColumnC()
        {
            float cx = DossierLayout.ColumnCCentreX;

            // WAS a plain decorative label. Now the opener for the
            // attributes panel (owner item: "dedicated attributes screen
            // showing stat effects") -- same rect, same text, so promoting
            // it costs the header row no new space. Same row+panel shape as
            // Pack/Spells/Skills/Track's own openers (DeclareColumnARows'
            // own header), just this one lives in column C instead of A
            // because that is where the thing it opens already is.
            var attributesRow = Ui.Button("DossierAttributesRow", UiStrings.OverlayAttributes,
                    new UiVec(160f, 20f), 10,
                    Place.At(cx - DossierLayout.ContentCWidth * 0.5f + 80f,
                             DossierLayout.ColumnCTop - 10f))
                .NoChrome();
            AttributesRow = attributesRow;
            yield return attributesRow;

            yield return Ui.Solid("DossierAttributesRule", Rule,
                new UiVec(DossierLayout.ContentCWidth, 1f),
                Place.At(cx, DossierLayout.ColumnCTop - 24f)).AsDecor();

            // HOW MANY POINTS ARE WAITING, on the same line as the section
            // label. Without it the "+" buttons are the only thing saying a
            // point exists, and they are 22px each in the corner of a cell --
            // easy to have and never notice, which is how levelling came to
            // hand out something nobody could see.
            var unspent = Ui.Label("DossierUnspentPoints", UiString.Runtime,
                new UiVec(180f, 20f), 11, Accent,
                Place.At(cx + DossierLayout.ContentCWidth * 0.5f - 90f,
                         DossierLayout.ColumnCTop - 10f));
            UnspentPoints = unspent;
            yield return unspent;

            // Six generic cells. Which attribute lands where is decided per
            // character at runtime -- the handover wants them highest-first so
            // the shape of the build reads off the first row.
            for (int i = 0; i < SheetStats.Abilities.Length; i++)
            {
                int row = i / 3;
                int column = i % 3;
                float x = DossierLayout.AttributeCellCentreX(column);
                float y = DossierLayout.AttributeCellCentreY(row);

                var value = Ui.Label($"DossierAttrValue{i}", UiString.Runtime, new UiVec(90f, 36f), 30, Text,
                    Place.At(0f, 10f)).AsDecor();
                var keyLabel = Ui.Label($"DossierAttrKey{i}", UiString.Runtime, new UiVec(90f, 16f), 10, TextDim,
                    Place.At(0f, -18f)).AsDecor();

                var cell = Ui.Button($"DossierAttrCell{i}", UiString.Runtime,
                        // MINUS 2, because cells tiled edge to edge share a
                        // boundary and the overlap check reads a shared edge as
                        // an overlap -- rightly, since the later sibling would
                        // take clicks along it.
                        new UiVec(DossierLayout.AttributeCellWidth - 2f, DossierLayout.AttributeCellHeight - 2f), 1,
                        Place.At(x, y))
                    .NoChrome();
                // The "+" that spends a point into this score. Inactive in the
                // tree: it appears only when there is a point to spend, and a
                // permanently visible one on a character with none reads as
                // broken.
                float halfWidth = (DossierLayout.AttributeCellWidth - 2f) * 0.5f;
                float halfHeight = (DossierLayout.AttributeCellHeight - 2f) * 0.5f;
                var plus = Ui.Button($"DossierAttrPlus{i}", UiStrings.DossierSpendPoint,
                        new UiVec(DossierLayout.AttributePlusSize, DossierLayout.AttributePlusSize), 14,
                        Place.At(halfWidth - DossierLayout.AttributePlusInset,
                                 halfHeight - DossierLayout.AttributePlusInset))
                    .NoChrome()
                    .Inactive();
                // The "-" that refunds a point out of this score. Mirrored off
                // the plus across the cell's centre, same size and inset, same
                // inactive-until-shown treatment -- but gated per cell rather
                // than globally, since a refund can only come out of a score
                // that has something invested in it (see PaintStatSpending).
                var minus = Ui.Button($"DossierAttrMinus{i}", UiStrings.DossierRefundPoint,
                        new UiVec(DossierLayout.AttributePlusSize, DossierLayout.AttributePlusSize), 14,
                        Place.At(-(halfWidth - DossierLayout.AttributePlusInset),
                                 halfHeight - DossierLayout.AttributePlusInset))
                    .NoChrome()
                    .Inactive();

                cell.Children.Add(value);
                cell.Children.Add(keyLabel);
                cell.Children.Add(plus);
                cell.Children.Add(minus);

                AttributeCells.Add(cell);
                AttributeValues.Add(value);
                AttributeKeys.Add(keyLabel);
                AttributePluses.Add(plus);
                AttributeMinuses.Add(minus);
                yield return cell;
            }

            yield return Ui.Solid("DossierStatListRule", Rule,
                new UiVec(DossierLayout.ContentCWidth, 1f),
                Place.At(cx, DossierLayout.StatListTop)).AsDecor();

            // ONE ROW PER SheetStats.Derived ENTRY. This is the dynamic list:
            // adding a stat there adds a row here, and the guard in Build
            // refuses a list that no longer fits.
            for (int i = 0; i < SheetStats.Derived.Length; i++)
            {
                var stat = SheetStats.Derived[i];
                float y = DossierLayout.StatRowCentreY(i);

                // The highlight bar for the attribute-hover link. Inactive by
                // default; the controller raises the rows the hovered attribute
                // actually feeds.
                var highlight = Ui.Solid($"DossierStatHighlight{i}", "#B9A2D61F",
                        new UiVec(DossierLayout.ContentCWidth, DossierLayout.StatRowHeight - 2f),
                        Place.At(cx, y))
                    .Inactive().AsDecor();

                var name = Ui.Label($"DossierStatName{i}", SheetStats.LabelFor(stat),
                    new UiVec(170f, 22f), 15, Text,
                    Place.At(cx - DossierLayout.ContentCWidth * 0.5f + 85f, y)).AsDecor();

                var preview = Ui.Label($"DossierStatPreview{i}", UiString.Runtime, new UiVec(84f, 20f), 13,
                    TextDim, Place.At(cx + DossierLayout.ContentCWidth * 0.5f - 130f, y)).AsDecor();

                var value = Ui.Label($"DossierStatValue{i}", UiString.Runtime, new UiVec(76f, 22f), 15, Text,
                    Place.At(cx + DossierLayout.ContentCWidth * 0.5f - 40f, y)).AsDecor();

                var rule = Ui.Solid($"DossierStatRule{i}", RuleSoft,
                    new UiVec(DossierLayout.ContentCWidth, 1f),
                    Place.At(cx, y - DossierLayout.StatRowHeight * 0.5f)).AsDecor();

                StatHighlights.Add(highlight);
                StatNames.Add(name);
                StatValues.Add(value);
                StatPreviews.Add(preview);

                yield return highlight;
                yield return name;
                yield return preview;
                yield return value;
                yield return rule;
            }
        }

        // ---- the attributes panel (modal) ----------------------------------------------
        //
        // "Dedicated attributes screen showing stat effects, with
        // mouse/gamepad allocation and reallocation" -- the owner item this
        // panel exists for. Six rows, one per ability score, EACH row
        // showing the score, the invested points, and what it does in
        // numbers pulled from AbilityEffectDescriptions (Domain/Stats) --
        // the same derivation functions combat itself reads, never a
        // restated figure. Rows are painted by
        // CharacterDossierController.PaintAttributesPanel in EXACTLY
        // _cellOrder's order, the same order the compact grid already uses,
        // so Spend(int)/Refund(int) need no second overload for this panel.
        private UiNode BuildAttributesPanel()
        {
            const float cx = 0f;
            var children = new List<UiNode>();

            // Flush to the content edge -- offset by exactly the box's own
            // half-width, same convention BuildColumnC's header label uses
            // against ContentCWidth, so the box's left edge lands ON the
            // content edge rather than at an arbitrary offset that can
            // overhang it (AUDIT: the first version of this offset by a
            // flat 90px against a 300px-wide box and overhung the card by
            // 12px at every aspect).
            const float titleWidth = 280f;
            children.Add(Ui.Label("DossierAttributesTitle", UiStrings.DossierAttributesTitle,
                    new UiVec(titleWidth, 26f), 18, AccentHi,
                    Place.At(cx - DossierLayout.AttributesContentWidth * 0.5f + titleWidth * 0.5f,
                             DossierLayout.AttributesTop))
                .AsDecor());

            var closeShape = Ui.PlateShapeFor(110f, 28f);
            var closeSize = new UiVec(28f * Ui.PlateAspect(closeShape), 28f);
            var close = Ui.Button("DossierAttributesClose", UiStrings.OverlayPackClose, closeSize, 15,
                    Place.At(cx + DossierLayout.AttributesContentWidth * 0.5f - closeSize.X * 0.5f,
                             DossierLayout.AttributesTop - 2f))
                .Themed(ButtonTheme.Silver);
            AttributesCloseButton = close;
            children.Add(close);

            children.Add(Ui.Solid("DossierAttributesHeaderRule", Rule,
                new UiVec(DossierLayout.AttributesContentWidth, 1f),
                Place.At(cx, DossierLayout.AttributesTop - 26f)).AsDecor());

            // Points waiting, on its own line -- same words PaintStatSpending
            // already puts on the compact grid's own UnspentPoints label, so
            // the two can never disagree about what "3 points" means. Same
            // flush-to-content-edge convention as the title above.
            const float unspentWidth = 280f;
            var unspent = Ui.Label("DossierAttributesUnspentPoints", UiString.Runtime,
                    new UiVec(unspentWidth, 22f), 14, Accent,
                    Place.At(cx - DossierLayout.AttributesContentWidth * 0.5f + unspentWidth * 0.5f,
                             DossierLayout.AttributesSubHeaderY))
                .AsDecor()
                .TextAligned(UiTextAlign.TopLeft);
            AttributesUnspentPoints = unspent;
            children.Add(unspent);

            // Why a minus might not be doing anything, spoken rather than
            // left for the player to guess at a quiet button -- see
            // DossierAttributesLocked's own comment. Inactive by default;
            // the controller shows it only while the lock actually applies.
            var lockNote = Ui.Label("DossierAttributesLockNote", UiStrings.DossierAttributesLocked,
                    new UiVec(DossierLayout.AttributesContentWidth * 0.5f - 20f, 22f), 13, TextDim,
                    Place.At(cx + DossierLayout.AttributesContentWidth * 0.25f + 10f,
                             DossierLayout.AttributesSubHeaderY))
                .AsDecor()
                .Inactive()
                .TextAligned(UiTextAlign.Right);
            AttributesLockNote = lockNote;
            children.Add(lockNote);

            children.Add(Ui.Solid("DossierAttributesSubHeaderRule", RuleSoft,
                new UiVec(DossierLayout.AttributesContentWidth, 1f),
                Place.At(cx, DossierLayout.AttributesRowsTop + 6f)).AsDecor());

            float textCx = DossierLayout.AttributesTextCentreX;
            float textWidth = DossierLayout.AttributesTextWidth;

            // NAME/EFFECT Y ARE ROW-LOCAL, not absolute -- both labels are
            // children of `row` below, positioned relative to ITS centre
            // (0,0 in its own local space), the same relative-offset
            // convention DossierAttrValue{i}/DossierAttrKey{i} already use
            // against their own cell.
            float nameY = DossierLayout.AttributesRowHeight * 0.5f - 20f;
            float effectY = nameY - 16f - 4f - 18f;

            for (int i = 0; i < SheetStats.Abilities.Length; i++)
            {
                float y = DossierLayout.AttributesRowCentreY(i);

                // THE ROW ITSELF: a plain Panel in the tree (no Button, no
                // Selectable) -- ScreenRegistry.WireDossier promotes it to
                // an AttributeRow (CharacterDossierController's own
                // Button-derived component) at build time, the exact shape
                // ScreenRegistry.WireOptions already uses for OptionRow.
                // Building it as a Button here instead would leave a SECOND
                // Selectable fighting the first one over the same
                // GameObject the moment WireDossier attaches AttributeRow.
                var row = Ui.Panel($"DossierAttrRow{i}",
                        Place.At(cx, y),
                        UiSize.Fixed(DossierLayout.AttributesContentWidth, DossierLayout.AttributesRowHeight - 2f))
                    .NoChrome();

                // ACTIVE in the tree. They were built .Inactive() and nothing
                // ever switched them on -- PaintAttributesPanel only sets
                // their text -- so all six rows drew blank (QA 2026-09-26
                // #203.1). The modal itself is what starts hidden; its
                // labels have no state in which they should be off.
                var name = Ui.Label($"DossierAttrRowName{i}", UiString.Runtime,
                        new UiVec(textWidth, 20f), 16, Text, Place.At(textCx, nameY))
                    .AsDecor()
                    .TextAligned(UiTextAlign.TopLeft);

                var effect = Ui.Label($"DossierAttrRowEffect{i}", UiString.Runtime,
                        new UiVec(textWidth, 40f), 13, TextDim, Place.At(textCx, effectY))
                    .AsDecor()
                    .TextAligned(UiTextAlign.TopLeft);

                // The two steppers, children of the row like the compact
                // grid's own plus/minus -- a click routes to whichever one
                // is actually under the pointer because uGUI hit-tests the
                // deeper object first, so they take clicks meant for them
                // even though the row beneath spans the same area.
                var minus = Ui.Button($"DossierAttrRowMinus{i}", UiStrings.DossierRefundPoint,
                        new UiVec(DossierLayout.AttributesStepSize, DossierLayout.AttributesStepSize), 16,
                        Place.At(DossierLayout.AttributesStepMinusX, 0f))
                    .NoChrome()
                    .Inactive();

                var plus = Ui.Button($"DossierAttrRowPlus{i}", UiStrings.DossierSpendPoint,
                        new UiVec(DossierLayout.AttributesStepSize, DossierLayout.AttributesStepSize), 16,
                        Place.At(DossierLayout.AttributesStepPlusX, 0f))
                    .NoChrome()
                    .Inactive();

                // CHILDREN of the row, not siblings over it -- same
                // containment DossierAttrCell{i} already uses for its own
                // value/key labels and plus/minus (that comment's own
                // reasoning: a child is contained by construction, so the
                // overlap audit and uGUI's own hit routing both agree it
                // belongs to the row rather than fighting it for the same
                // rect).
                row.Children.Add(name);
                row.Children.Add(effect);
                row.Children.Add(minus);
                row.Children.Add(plus);

                AttributeRowSteps.Add(row);
                AttributeRowNames.Add(name);
                AttributeRowEffects.Add(effect);
                AttributeRowPluses.Add(plus);
                AttributeRowMinuses.Add(minus);

                children.Add(row);
            }

            var card = Ui.Sprite("DossierAttributesCard", null, Place.At(0f, 0f),
                    UiSize.Fixed(DossierLayout.AttributesCardWidth, DossierLayout.AttributesCardHeight))
                .Coloured(PackGround);
            foreach (var child in children) card.Children.Add(child);

            var modal = Ui.Modal("DossierAttributesModal", "#05030AD9", card).Inactive();
            AttributesPanel = modal;
            return modal;
        }

        // ---- the shared tooltip --------------------------------------------------------

        // OWNER ITEM (2026-09-22): "readable, roughly square item tooltips
        // replacing the purple rectangles". The bespoke 300x480 sliver above
        // (its own history is in git log, not restated here) is retired in
        // favour of ItemComparisonPanel -- the shop's own reference shape,
        // #1D1226F2 fill + Ui.Rim hairline at ~420x420, title font 20, body
        // font 15 -- rather than a second hand-tuned rectangle. ONE builder,
        // two callers: ShopScreen's ShopDetailPanel and this DossierTooltip.
        //
        // The name prefix IS the node-name contract: ItemComparisonPanel.Build
        // emits "<prefix>", "<prefix>Title" and "<prefix>Body", so passing
        // "DossierTooltip" reproduces the exact three names
        // CharacterDossierController's ShowTooltip/PlaceTooltip and
        // TooltipPlacement.Beside already key off -- no controller change
        // needed. Inactive().AsDecor() are re-applied here because Build's
        // own caller (ShopScreen) wants a STANDING panel, always active; a
        // hover tooltip is the opposite by construction (Ui.Tooltip's own
        // header explains why: hidden until hovered, and never allowed to
        // steal the click meant for the thing underneath it).
        private UiNode BuildTooltip()
        {
            var built = ItemComparisonPanel.Build("DossierTooltip", Place.At(0f, 0f),
                new UiVec(DossierLayout.TooltipWidth, DossierLayout.TooltipMaxHeight),
                titleHeight: DossierLayout.TooltipTitleHeight,
                titleFontSize: 20, titleHex: AccentHi,
                bodyFontSize: 15, bodyHex: TextDim);

            TooltipTitle = built.Title;
            TooltipBody = built.Body;

            var panel = built.Panel.Inactive().AsDecor();
            Tooltip = panel;
            return panel;
        }
    }
}
