using System.Collections.Generic;
using System.Linq;
using PrincesPalace.Domain.Equipment;

namespace PrincesPalace.Domain.UiKit.Screens
{
    // The character sheet, rebuilt to the "Dossier" handover: identity and pack
    // on the left, a mannequin with its slots in the middle, the numbers on the
    // right.
    //
    // REPLACES CharacterOverlayScreen, and lives inside the system menu's
    // Character and Inventory panes rather than being its own modal -- the two
    // tabs are two doors into this one screen, exactly as C and I are today.
    //
    // Authored AT the menu's 1600x804 content pane and filling it. It used to
    // sit at the handover's own 1360x766, centred, which left 118px of dead
    // margin a side and all three columns stopping short of the floor. Nothing
    // scales: DossierLayout re-proportions the columns and scales the loadout
    // stage as one unit, which is what the handover's rule was protecting.
    //
    // WHAT IS NOT HERE, and why: the handover's Dodge, Carried, Shop prices and
    // Party morale rows are gone. None of them exists in this game -- there is
    // no dodge, no carry weight, no price modifier and no morale -- and printing
    // four numbers with no source would be four lies a player cannot check. The
    // stat list is built from SheetStats.Derived instead, so it is exactly the
    // stats that are real, and adding one later is one entry there.
    public sealed class CharacterDossierScreen
    {
        public const string PortraitKey = "UI/CharacterOverlay/Processed/armour_stand.png";
        // Baked by ProceduralSpriteBaker; "proc:" names a committed PNG rather
        // than a texture generated at runtime.
        public const string VeilKey = "proc:dossier_veil";

        public const string MannequinKey = "UI/CharacterOverlay/Processed/armour_stand.png";

        // The same figure traced to a line, generated by tools/outline_silhouette.py
        // from the fill's own alpha, so the two can never drift apart.
        public const string MannequinOutlineKey =
            "UI/CharacterOverlay/Processed/armour_stand_outline.png";

        // ---- tokens, from the handover's table ----------------------------------

        public const string Rule = "#C8B4DE29";          // rgba(200,180,222,.16)
        public const string RuleSoft = "#C8B4DE12";      // rgba(200,180,222,.07)
        public const string TextHi = "#F4EEFA";
        public const string Text = "#F0E8F8";
        public const string TextDim = "#D6C8E86B";       // rgba(214,200,232,.42)
        public const string TextFaint = "#D6C8E852";     // rgba(214,200,232,.32)
        public const string Accent = "#B9A2D6";
        public const string AccentHi = "#D8C2F0";
        public const string SlotBorder = "#BEA8D652";
        public const string SlotEmptyBorder = "#C8B4DE1F";
        public const string PackGround = "#160E1E";
        public const string Ground = "#120A18FA";

        public UiNode Root;

        public NodeRef Portrait;
        public NodeRef CharacterName;
        public NodeRef SubLine;
        public NodeRef XpFill;
        public NodeRef XpRemaining;
        public NodeRef PrevCharacterButton;
        public NodeRef NextCharacterButton;

        public NodeRef SkillsRow;
        public NodeRef SkillsCount;
        public NodeRef PackRow;
        public NodeRef PackChevron;

        public NodeRef PackPanel;
        public NodeRef PackCloseButton;
        public List<NodeRef> PackFilterTabs = new List<NodeRef>();
        public List<NodeRef> PackCells = new List<NodeRef>();
        public List<NodeRef> PackIcons = new List<NodeRef>();
        public List<NodeRef> PackCounts = new List<NodeRef>();
        public List<NodeRef> PackRarityTicks = new List<NodeRef>();

        // The name beside each icon, which two-abreast rows have room for and
        // a four-across grid of squares did not.
        public List<NodeRef> PackNames = new List<NodeRef>();

        // Underlines, one per sort key, showing which ordering is live -- the
        // same marker the system menu's tab bar uses, for the same reason.
        public List<NodeRef> PackSortUnderlines = new List<NodeRef>();

        public NodeRef PackScrollTrack;
        public NodeRef PackScrollThumb;
        public NodeRef CarriedValue;

        // Indexed by EquipmentSlots.All.
        public List<NodeRef> SlotCells = new List<NodeRef>();
        public List<NodeRef> SlotIcons = new List<NodeRef>();
        public List<NodeRef> SlotLabels = new List<NodeRef>();
        public List<NodeRef> SlotRarityTicks = new List<NodeRef>();
        public List<NodeRef> SlotBlockedCaptions = new List<NodeRef>();

        // Six cells, filled highest-first at runtime -- which attribute lands
        // in which cell is a per-character question, so the nodes stay generic.
        public List<NodeRef> AttributeCells = new List<NodeRef>();
        public List<NodeRef> AttributeValues = new List<NodeRef>();
        public List<NodeRef> AttributeKeys = new List<NodeRef>();

        // Indexed by SheetStats.Derived.
        public List<NodeRef> StatRows = new List<NodeRef>();
        public List<NodeRef> StatNames = new List<NodeRef>();
        public List<NodeRef> StatValues = new List<NodeRef>();
        public List<NodeRef> StatPreviews = new List<NodeRef>();
        public List<NodeRef> StatHighlights = new List<NodeRef>();

        public NodeRef Tooltip;
        public NodeRef TooltipTitle;
        public NodeRef TooltipBody;

        public static CharacterDossierScreen Build()
        {
            var screen = new CharacterDossierScreen();

            // The stat list is generated from SheetStats, so it can outgrow its
            // column the moment somebody adds a row. Same guard, same reasoning
            // as the system menu's tab bar.
            int statCount = SheetStats.Derived.Length;
            if (!DossierLayout.StatListFits(statCount))
            {
                throw new System.InvalidOperationException(
                    $"The dossier has {statCount} stat rows but column C holds {DossierLayout.MaxStatRows()} " +
                    $"at {DossierLayout.StatRowHeight}px. Shorten the rows, lengthen the panel, or the list " +
                    "needs to scroll - it cannot simply be given another entry.");
            }

            var children = new List<UiNode>();

            // ITS OWN GROUND. The handover gives this panel #120a18, and it
            // needs one for a reason beyond taste: it opens over the hub and the
            // fight, and a transparent sheet let a painted background read
            // straight through the numerals.
            children.Add(Ui.Solid("DossierGround", Ground,
                    new UiVec(DossierLayout.Width, DossierLayout.Height), Place.At(0f, 0f))
                .AsDecor());

            // Light from above, over the flat ground.
            //
            // The ground alone gave the panel no hierarchy: three columns of
            // equal weight on one even field. This lifts the top edge, where
            // the portrait and the column headings are, and leaves the bottom
            // honest black so the stat rows stay quiet. Violet rather than
            // white so it reads as the palette's own light and not as a
            // grey wash laid over it.
            children.Add(Ui.Sprite("DossierVeil", VeilKey,
                    Place.At(0f, 0f), UiSize.Fixed(DossierLayout.Width, DossierLayout.Height))
                .Coloured("#6A54902B")
                .AsDecor());

            children.AddRange(screen.BuildColumnA());
            children.AddRange(screen.BuildColumnB());
            children.AddRange(screen.BuildColumnC());

            // The two column dividers.
            children.Add(Ui.Solid("DossierDividerAB", Rule,
                new UiVec(1f, DossierLayout.Height - DossierLayout.PadY * 2f),
                Place.At(DossierLayout.DividerAtoB, 0f)).AsDecor());
            children.Add(Ui.Solid("DossierDividerBC", Rule,
                new UiVec(1f, DossierLayout.Height - DossierLayout.PadY * 2f),
                Place.At(DossierLayout.DividerBtoC, 0f)).AsDecor());

            // The pack covers column A entirely, so it is declared AFTER it.
            children.Add(screen.BuildPackPanel());

            // And the tooltip over everything.
            children.Add(screen.BuildTooltip());

            screen.Root = Ui.Panel("CharacterDossier", Place.At(0f, 0f),
                UiSize.Fixed(DossierLayout.Width, DossierLayout.Height), children);
            return screen;
        }

        // ---- column A: identity ---------------------------------------------------

        private IEnumerable<UiNode> BuildColumnA()
        {
            float cx = DossierLayout.ColumnACentreX;

            var portrait = Ui.Sprite("DossierPortrait", PortraitKey,
                    Place.At(cx, DossierLayout.PortraitCentreY),
                    UiSize.Fixed(DossierLayout.ContentAWidth, DossierLayout.PortraitHeight))
                .Coloured("#6640884D")
                .AsDecor();
            Portrait = portrait;
            yield return portrait;

            var name = Ui.Label("DossierName", UiString.Runtime,
                new UiVec(DossierLayout.ContentAWidth - 76f, 42f), 34, TextHi,
                Place.At(cx, DossierLayout.NameCentreY));
            CharacterName = name;
            yield return name;

            // The roster arrows the old sheet had. The handover does not show
            // them -- it draws one character -- but the game has five and no
            // other way to reach them from here, so dropping them would be a
            // capability regression dressed as a redesign.
            var prev = Ui.Button("DossierPrevCharacter", UiStrings.OverlayPrev, new UiVec(34f, 34f), 18,
                Place.At(cx - DossierLayout.ContentAWidth * 0.5f + 17f, DossierLayout.NameCentreY)).NoChrome();
            var next = Ui.Button("DossierNextCharacter", UiStrings.OverlayNext, new UiVec(34f, 34f), 18,
                Place.At(cx + DossierLayout.ContentAWidth * 0.5f - 17f, DossierLayout.NameCentreY)).NoChrome();
            PrevCharacterButton = prev;
            NextCharacterButton = next;
            yield return prev;
            yield return next;

            var sub = Ui.Label("DossierSubLine", UiString.Runtime,
                new UiVec(DossierLayout.ContentAWidth, 24f), 14, Accent,
                Place.At(cx, DossierLayout.SubLineCentreY));
            SubLine = sub;
            yield return sub;

            // XP: label, a 3px track with its fill, and what is left.
            yield return Ui.Label("DossierXpLabel", UiStrings.OverlayXp, new UiVec(30f, 16f), 10, TextDim,
                Place.At(cx - DossierLayout.ContentAWidth * 0.5f + 15f, DossierLayout.XpRowCentreY)).AsDecor();

            float trackWidth = DossierLayout.XpTrackWidth;
            float trackLeft = cx + DossierLayout.XpTrackLeft;
            yield return Ui.Solid("DossierXpTrack", "#C8B4DE24",
                new UiVec(trackWidth, 3f),
                Place.At(trackLeft + trackWidth * 0.5f, DossierLayout.XpRowCentreY)).AsDecor();

            var fill = Ui.Solid("DossierXpFill", Accent, new UiVec(trackWidth, 3f),
                    Place.At(trackLeft, DossierLayout.XpRowCentreY, new UiVec(0f, 0.5f)))
                .AsDecor();
            XpFill = fill;
            yield return fill;

            var left = Ui.Label("DossierXpRemaining", UiString.Runtime, new UiVec(70f, 16f), 11, TextDim,
                Place.At(cx + DossierLayout.ContentAWidth * 0.5f - 35f, DossierLayout.XpRowCentreY));
            XpRemaining = left;
            yield return left;

            // The two nav rows. BuildNavRow assigns its own refs -- an iterator
            // cannot carry `out` parameters, and threading them back through the
            // caller bought nothing.
            yield return BuildNavRow("Skills", UiStrings.OverlaySkills, DossierLayout.SkillsRowCentreY);
            yield return BuildNavRow("Pack", UiStrings.OverlayPack, DossierLayout.PackRowCentreY);
        }

        private UiNode BuildNavRow(string key, UiString label, float centreY)
        {
            float cx = DossierLayout.ColumnACentreX;

            var button = Ui.Button($"Dossier{key}Row", UiString.Runtime,
                    new UiVec(DossierLayout.ContentAWidth, DossierLayout.NavRowHeight), 1,
                    Place.At(cx, centreY))
                .NoChrome();

            button.Children.Add(Ui.Solid($"Dossier{key}RowRule", Rule,
                new UiVec(DossierLayout.ContentAWidth, 1f),
                Place.At(0f, DossierLayout.NavRowHeight * 0.5f - 0.5f)).AsDecor());

            // ...RowName, NOT ...RowLabel. UiEmitter names a button's own
            // caption "<button>Label", so a child called that collides with an
            // object the tree never declares and every lookup by name silently
            // takes the emitter's empty one -- AUDIT #39, caught here by the
            // check that finding added.
            button.Children.Add(Ui.Label($"Dossier{key}RowName", label,
                new UiVec(160f, 24f), 17, Text,
                Place.At(-DossierLayout.ContentAWidth * 0.5f + 82f, 0f)).AsDecor());

            var countLabel = Ui.Label($"Dossier{key}RowCount", UiString.Runtime,
                new UiVec(90f, 20f), 12, TextDim,
                Place.At(DossierLayout.ContentAWidth * 0.5f - 66f, 0f)).AsDecor();
            button.Children.Add(countLabel);

            var chev = Ui.Label($"Dossier{key}RowChevron", UiString.Runtime,
                new UiVec(20f, 24f), 16, Accent,
                Place.At(DossierLayout.ContentAWidth * 0.5f - 12f, 0f)).AsDecor();
            button.Children.Add(chev);

            // Assigned here rather than returned, so the two call sites stay
            // one line each.
            if (key == "Skills") { SkillsRow = button; SkillsCount = countLabel; }
            else { PackRow = button; PackChevron = chev; }

            return button;
        }

        // ---- column A, covered: the pack -------------------------------------------

        private static UiString SortLabel(BagSortKey key)
        {
            switch (key)
            {
                case BagSortKey.Plus: return UiStrings.PackSortPlus;
                case BagSortKey.Name: return UiStrings.PackSortName;
                default: return UiStrings.PackSortTier;
            }
        }

        private UiNode BuildPackPanel()
        {
            // ZERO, not the column centre. These are children OF the pack
            // panel, and the panel is itself placed at column A -- expressing
            // them in dossier coordinates offset every one of them twice, which
            // the child-containment audit caught as a 339px escape rather than
            // letting it ship as a pack drawn off the side of the screen.
            const float cx = 0f;
            var children = new List<UiNode>();

            children.Add(Ui.Label("DossierPackTitle", UiStrings.OverlayPackTitle,
                new UiVec(170f, 22f), 13, TextFaint,
                Place.At(cx - DossierLayout.ContentAWidth * 0.5f + 75f, DossierLayout.ColumnATop - 10f)).AsDecor());

            var close = Ui.Button("DossierPackClose", UiStrings.OverlayPackClose, new UiVec(110f, 28f), 15,
                    Place.At(cx + DossierLayout.ContentAWidth * 0.5f - 55f, DossierLayout.ColumnATop - 12f))
                .NoChrome();
            PackCloseButton = close;
            children.Add(close);

            children.Add(Ui.Solid("DossierPackHeaderRule", Rule,
                new UiVec(DossierLayout.ContentAWidth, 1f),
                Place.At(cx, DossierLayout.ColumnATop - 26f)).AsDecor());

            // HOW THE PACK IS ORDERED, chosen by the player.
            //
            // Three keys, not the four that were asked for: rarity is derived
            // from tier by RarityBands, so a rarity button would produce the
            // tier button's list with the precision thrown away. Two controls
            // that do the same thing is the same failure as one that does
            // nothing. See BagSort.
            for (int i = 0; i < BagSort.All.Length; i++)
            {
                float x = cx - DossierLayout.ContentAWidth * 0.5f
                          + DossierLayout.PackSortButtonWidth * (i + 0.5f);

                var tab = Ui.Button($"DossierPackSort{i}", SortLabel(BagSort.All[i]),
                        new UiVec(DossierLayout.PackSortButtonWidth, DossierLayout.PackSortRowHeight), 14,
                        Place.At(x, DossierLayout.PackSortCentreY))
                    .NoChrome();

                var underline = Ui.Solid($"DossierPackSort{i}Underline", "#FFE0A8",
                        new UiVec(DossierLayout.PackSortButtonWidth - 24f, 2f),
                        Place.At(x, DossierLayout.PackSortCentreY - DossierLayout.PackSortRowHeight * 0.5f + 1f))
                    .Inactive()
                    .AsDecor();

                PackFilterTabs.Add(tab);
                PackSortUnderlines.Add(underline);
                children.Add(tab);
                children.Add(underline);
            }

            // TWO ABREAST, AND ONLY WHAT FITS. The cells are a WINDOW onto the
            // bag rather than its capacity: the controller binds cell i to item
            // i + offset, so a pack of any size is reachable by scrolling and a
            // 25th item is no longer simply absent.
            float cellW = DossierLayout.PackCellWidth;
            float cellH = DossierLayout.PackCellHeight;

            for (int i = 0; i < DossierLayout.PackVisibleCells; i++)
            {
                int col = i % (int)DossierLayout.PackColumns;
                int rowIndex = i / (int)DossierLayout.PackColumns;

                float x = cx + DossierLayout.PackCellCentreX(col);
                float y = DossierLayout.PackCellCentreY(rowIndex);

                // CENTRED AND ON TOP. Half again the size it was, because the
                // icon is what the eye actually sorts by.
                var icon = Ui.Sprite($"DossierPackIcon{i}", null,
                        new UiVec(DossierLayout.PackIconSize, DossierLayout.PackIconSize),
                        Place.At(0f, DossierLayout.PackIconCentreY))
                    .Inactive().AsDecor();

                var tick = Ui.Solid($"DossierPackTick{i}", "#7F8EA3", new UiVec(12f, 12f),
                    Place.At(-cellW * 0.5f + 9f, cellH * 0.5f - 9f)).Inactive().AsDecor();

                // UNDER the icon and the full width of the cell, which is the
                // whole point of the change: beside a 44px icon this had about
                // 110px, and a generated item's name does not fit in 110px at a
                // size anyone can read.
                // 15px, up from 11. The cell is twice the height it was and the
                // name owns the surplus, so the old size left it small text
                // floating in a large box -- which reads as worse, not better.
                var name = Ui.Label($"DossierPackName{i}", UiString.Runtime,
                        new UiVec(cellW - 12f, DossierLayout.PackNameHeight), 15, Text,
                        Place.At(0f, DossierLayout.PackNameCentreY))
                    .Inactive().AsDecor();

                // TOP right, not bottom: the name owns the bottom of the cell
                // now, and a count sitting in it would print across the words.
                var count = Ui.Label($"DossierPackCount{i}", UiString.Runtime, new UiVec(34f, 18f), 13,
                    "#E6DCF0BF", Place.At(cellW * 0.5f - 19f, cellH * 0.5f - 12f)).Inactive().AsDecor();

                var button = Ui.Button($"DossierPackCell{i}", UiString.Runtime, new UiVec(cellW, cellH), 1,
                        Place.At(x, y))
                    .NoChrome()
                    .Hovers(1.02f)
                    .AllowOverlap("an entry's icon, name and count sit inside their own row by construction");

                button.Children.Add(icon);
                button.Children.Add(tick);
                button.Children.Add(name);
                button.Children.Add(count);

                PackCells.Add(button);
                PackIcons.Add(icon);
                PackRarityTicks.Add(tick);
                PackNames.Add(name);
                PackCounts.Add(count);
                children.Add(button);
            }

            // The scrollbar. A track and a thumb the controller sizes and
            // moves, rather than a ScrollRect: there is no scrolling CONTENT
            // here to move -- the cells stay put and their CONTENTS change --
            // so a real viewport would be machinery around a list that does not
            // need one.
            var track = Ui.Solid("DossierPackScrollTrack", "#0E070CD9",
                    new UiVec(DossierLayout.PackScrollbarWidth, DossierLayout.PackTrackHeight),
                    Place.At(cx + DossierLayout.PackScrollbarCentreX, DossierLayout.PackTrackCentreY));

            var thumb = Ui.Solid("DossierPackScrollThumb", "#C8AAE666",
                    new UiVec(DossierLayout.PackScrollbarWidth, DossierLayout.PackTrackHeight),
                    Place.At(cx + DossierLayout.PackScrollbarCentreX, DossierLayout.PackTrackCentreY))
                .AsDecor();

            PackScrollTrack = track;
            PackScrollThumb = thumb;
            children.Add(track);
            children.Add(thumb);

            float footerY = -DossierLayout.HalfHeight + DossierLayout.PadY + 16f;
            children.Add(Ui.Solid("DossierPackFooterRule", Rule,
                new UiVec(DossierLayout.ContentAWidth, 1f), Place.At(cx, footerY + 18f)).AsDecor());
            children.Add(Ui.Label("DossierCarriedLabel", UiStrings.OverlayCarried, new UiVec(110f, 20f), 13,
                TextDim, Place.At(cx - DossierLayout.ContentAWidth * 0.5f + 55f, footerY)).AsDecor());

            var carried = Ui.Label("DossierCarriedValue", UiString.Runtime, new UiVec(110f, 20f), 14, Text,
                Place.At(cx + DossierLayout.ContentAWidth * 0.5f - 55f, footerY));
            CarriedValue = carried;
            children.Add(carried);

            // The PANEL sits over column A; its CHILDREN are relative to the
            // panel, hence cx = 0 above. Collapsing both onto one variable put
            // the whole pack in the middle of the screen, over the loadout.
            var panel = Ui.Sprite("DossierPackPanel", null,
                    Place.At(DossierLayout.ColumnACentreX, 0f),
                    UiSize.Fixed(DossierLayout.ColumnAWidth, DossierLayout.Height))
                .Coloured(PackGround)
                .Inactive()
                .AllowOverlap("the pack covers column A entirely - that IS the interaction");

            foreach (var child in children) panel.Children.Add(child);
            PackPanel = panel;
            return panel;
        }

        public const int PackCapacity = 24;

        // ---- column B: the loadout --------------------------------------------------

        private IEnumerable<UiNode> BuildColumnB()
        {
            yield return Ui.Label("DossierLoadoutLabel", UiStrings.OverlayLoadout,
                new UiVec(160f, 20f), 10, TextFaint,
                Place.At(DossierLayout.ColumnBCentreX - DossierLayout.StageWidth * 0.5f + 80f,
                         DossierLayout.HalfHeight - DossierLayout.PadY - 10f)).AsDecor();

            var mannequinAt = DossierLayout.FromStage(DossierLayout.MannequinLeft, DossierLayout.MannequinTop,
                DossierLayout.MannequinWidth, DossierLayout.MannequinHeight);

            // TWO LAYERS, and the split is the whole point.
            //
            // One solid shape at one opacity cannot do both jobs: raise it far
            // enough to define an edge and it becomes a purple slab competing
            // with the item art hung on it; drop it far enough to recede and
            // the figure stops existing. So the fill carries mass at almost
            // nothing, and a traced line carries the reading. That is also the
            // order the eye wants -- the equipment is the subject here and the
            // body is the armature it hangs from.
            yield return Ui.Sprite("DossierMannequinFill", MannequinKey,
                    Place.At(mannequinAt.X, mannequinAt.Y),
                    UiSize.Fixed(DossierLayout.MannequinWidth, DossierLayout.MannequinHeight))
                .Coloured("#B9A2D60E")
                .AsDecor();

            yield return Ui.Sprite("DossierMannequinOutline", MannequinOutlineKey,
                    Place.At(mannequinAt.X, mannequinAt.Y),
                    UiSize.Fixed(DossierLayout.MannequinWidth, DossierLayout.MannequinHeight))
                .Coloured("#EDE4FF5C")
                .AsDecor();

            foreach (var slot in EquipmentSlots.All)
            {
                foreach (var node in BuildSlot(slot)) yield return node;
            }
        }

        private IEnumerable<UiNode> BuildSlot(EquipmentSlot slot)
        {
            string key = EquipmentSlots.DisplayName(slot).Replace(" ", "");
            var at = DossierLayout.SlotAt(slot);

            // No hairline for the centred pair -- HEAD sits directly above the
            // figure's head and SHOES directly below its feet, so adjacency
            // already says which body part they belong to. Width 0 is how
            // DossierLayout.LeaderAt says so; emitting it anyway would be a
            // zero-sized graphic, which A6 refuses and is right to.
            var leaderAt = DossierLayout.LeaderAt(slot, out float leaderWidth);
            if (leaderWidth > 0f)
            {
                yield return Ui.Solid($"DossierLeader{key}", "#C8B4DE2E",
                    new UiVec(leaderWidth, 1f), Place.At(leaderAt.X, leaderAt.Y)).AsDecor();
            }

            // 6px of inset, down from 12. The slot box cannot grow -- the
            // figure's slots sit 98 authored units apart and the box plus its
            // caption already spend 88 of that -- so the only room left for the
            // ITEM is the padding inside the box it already has.
            // ABOVE THE CAPTION BAND, not across it. The caption moved inside
            // the socket and the icon filled the whole socket, so an equipped
            // sword was drawn straight through the word naming its slot --
            // "WEA(sword)ON 1". The icon gets the socket minus that band.
            const float CaptionBand = 22f;
            float iconSize = DossierLayout.SlotSize - CaptionBand;
            var icon = Ui.Sprite($"DossierSlotIcon{key}", null,
                new UiVec(iconSize, iconSize),
                Place.At(0f, CaptionBand * 0.5f)).Inactive().AsDecor();

            var tick = Ui.Solid($"DossierSlotTick{key}", "#7F8EA3", new UiVec(11f, 11f),
                Place.At(-DossierLayout.SlotSize * 0.5f + 7f, DossierLayout.SlotSize * 0.5f - 7f))
                .Inactive().AsDecor();

            // The blocked caption. A two-handed weapon must never leave the off
            // hand looking merely empty -- the player has to see WHY.
            var blocked = Ui.Label($"DossierSlotBlocked{key}", UiStrings.OverlayTwoHanded,
                new UiVec(DossierLayout.SlotSize - 8f, 26f), 9, TextDim, Place.At(0f, 0f))
                .Inactive().AsDecor();

            var cell = Ui.Button($"DossierSlot{key}", UiString.Runtime,
                    new UiVec(DossierLayout.SlotSize, DossierLayout.SlotSize), 1,
                    Place.At(at.X, at.Y))
                .NoChrome()
                .Hovers(1.05f)
                .AllowOverlap("a slot stands on the mannequin and its own leader line");
            cell.Children.Add(icon);
            cell.Children.Add(tick);
            cell.Children.Add(blocked);

            // THE SOCKET'S OWN FRAME, which the handover specified and nothing
            // ever drew: SlotEmptyBorder and SlotBorder have sat in the token
            // table above, declared and referenced by nothing, since the screen
            // was written.
            //
            // Without it an unequipped slot renders as literally nothing -- the
            // loadout was a column of captions at the panel's edge with a
            // leader stub floating near the figure and empty space between them,
            // which is what "the silhouette still looks very weird" was about.
            // Growing the boxes did not help while they were invisible.
            //
            // Drawn at the empty weight for every slot. Swapping to SlotBorder
            // when something is worn needs the controller to hold four node refs
            // per slot, which is a bigger change than making the socket visible
            // at all -- so SlotBorder stays unused for now, and knowingly.
            foreach (var edge in Ui.Rim($"DossierSlot{key}",
                         new UiVec(DossierLayout.SlotSize, DossierLayout.SlotSize), SlotEmptyBorder))
            {
                cell.Children.Add(edge);
            }

            // INSIDE the socket, along its bottom edge.
            //
            // Under the box it spent vertical room the box needed; beside it,
            // once the boxes moved out to their files, the word ended up an
            // inch from the socket it named with nothing between them. Inside,
            // the socket and its word are one object and the files can sit
            // wherever the figure leaves room.
            var label = Ui.Label($"DossierSlotLabel{key}", UiString.Runtime,
                new UiVec(DossierLayout.SlotSize - 8f, 16f), 11, TextDim,
                Place.At(at.X, at.Y - DossierLayout.SlotSize * 0.5f + 11f)).AsDecor();

            SlotCells.Add(cell);
            SlotIcons.Add(icon);
            SlotRarityTicks.Add(tick);
            SlotBlockedCaptions.Add(blocked);
            SlotLabels.Add(label);

            yield return cell;
            yield return label;
        }

        // ---- column C: the numbers ---------------------------------------------------

        private IEnumerable<UiNode> BuildColumnC()
        {
            float cx = DossierLayout.ColumnCCentreX;

            yield return Ui.Label("DossierAttributesLabel", UiStrings.OverlayAttributes,
                new UiVec(160f, 20f), 10, TextFaint,
                Place.At(cx - DossierLayout.ContentCWidth * 0.5f + 80f,
                         DossierLayout.ColumnCTop - 10f)).AsDecor();

            yield return Ui.Solid("DossierAttributesRule", Rule,
                new UiVec(DossierLayout.ContentCWidth, 1f),
                Place.At(cx, DossierLayout.ColumnCTop - 24f)).AsDecor();

            // Six generic cells. Which attribute lands where is decided per
            // character at runtime -- the handover wants them highest-first so
            // the shape of the build reads off the first row.
            for (int i = 0; i < SheetStats.Abilities.Length; i++)
            {
                int row = i / 3;
                int column = i % 3;
                float x = DossierLayout.AttributeCellCentreX(column);
                float y = DossierLayout.AttributeCellCentreY(row);

                var value = Ui.Label($"DossierAttrValue{i}", UiString.Runtime, new UiVec(90f, 36f), 30, Text,
                    Place.At(0f, 10f)).AsDecor();
                var keyLabel = Ui.Label($"DossierAttrKey{i}", UiString.Runtime, new UiVec(90f, 16f), 10, TextDim,
                    Place.At(0f, -18f)).AsDecor();

                var cell = Ui.Button($"DossierAttrCell{i}", UiString.Runtime,
                        // MINUS 2, because cells tiled edge to edge share a
                        // boundary and the overlap check reads a shared edge as
                        // an overlap -- rightly, since the later sibling would
                        // take clicks along it.
                        new UiVec(DossierLayout.AttributeCellWidth - 2f, DossierLayout.AttributeCellHeight - 2f), 1,
                        Place.At(x, y))
                    .NoChrome();
                cell.Children.Add(value);
                cell.Children.Add(keyLabel);

                AttributeCells.Add(cell);
                AttributeValues.Add(value);
                AttributeKeys.Add(keyLabel);
                yield return cell;
            }

            yield return Ui.Solid("DossierStatListRule", Rule,
                new UiVec(DossierLayout.ContentCWidth, 1f),
                Place.At(cx, DossierLayout.StatListTop)).AsDecor();

            // ONE ROW PER SheetStats.Derived ENTRY. This is the dynamic list:
            // adding a stat there adds a row here, and the guard in Build
            // refuses a list that no longer fits.
            for (int i = 0; i < SheetStats.Derived.Length; i++)
            {
                var stat = SheetStats.Derived[i];
                float y = DossierLayout.StatRowCentreY(i);

                // The highlight bar for the attribute-hover link. Inactive by
                // default; the controller raises the rows the hovered attribute
                // actually feeds.
                var highlight = Ui.Solid($"DossierStatHighlight{i}", "#B9A2D61F",
                        new UiVec(DossierLayout.ContentCWidth, DossierLayout.StatRowHeight - 2f),
                        Place.At(cx, y))
                    .Inactive().AsDecor();

                var name = Ui.Label($"DossierStatName{i}", SheetStats.LabelFor(stat),
                    new UiVec(170f, 22f), 15, Text,
                    Place.At(cx - DossierLayout.ContentCWidth * 0.5f + 85f, y)).AsDecor();

                var preview = Ui.Label($"DossierStatPreview{i}", UiString.Runtime, new UiVec(84f, 20f), 13,
                    TextDim, Place.At(cx + DossierLayout.ContentCWidth * 0.5f - 130f, y)).AsDecor();

                var value = Ui.Label($"DossierStatValue{i}", UiString.Runtime, new UiVec(76f, 22f), 15, Text,
                    Place.At(cx + DossierLayout.ContentCWidth * 0.5f - 40f, y)).AsDecor();

                var rule = Ui.Solid($"DossierStatRule{i}", RuleSoft,
                    new UiVec(DossierLayout.ContentCWidth, 1f),
                    Place.At(cx, y - DossierLayout.StatRowHeight * 0.5f)).AsDecor();

                StatHighlights.Add(highlight);
                StatRows.Add(highlight);
                StatNames.Add(name);
                StatValues.Add(value);
                StatPreviews.Add(preview);

                yield return highlight;
                yield return name;
                yield return preview;
                yield return value;
                yield return rule;
            }
        }

        // ---- the shared tooltip --------------------------------------------------------

        private UiNode BuildTooltip()
        {
            var title = Ui.Label("DossierTooltipTitle", UiString.Runtime, new UiVec(270f, 26f), 18, AccentHi,
                Place.At(0f, 44f)).AsDecor();
            var body = Ui.Label("DossierTooltipBody", UiString.Runtime, new UiVec(270f, 84f), 13, TextDim,
                Place.At(0f, -14f)).AsDecor();

            TooltipTitle = title;
            TooltipBody = body;

            // a tooltip floats over whatever it has to - it is transient and
            // takes no clicks
            var panel = Ui.Sprite("DossierTooltip", null, Place.At(0f, 0f), UiSize.Fixed(290f, 130f))
                .Coloured("#1D1226F2")
                .Inactive()
                .AsDecor();
            panel.Children.Add(title);
            panel.Children.Add(body);
            Tooltip = panel;
            return panel;
        }
    }

    // The pack's filter tabs, in one list so a new category is one entry.
    public static class PackFilters
    {
        public static readonly UiString[] All =
        {
            UiStrings.PackFilterAll,
            UiStrings.PackFilterArmour,
            UiStrings.PackFilterWeapons,
            UiStrings.PackFilterSalves,
        };
    }
}
