#!/usr/bin/env python3
"""Generate the bug-hunt obligation manifest, docs/hunt/MANIFEST.md.

Why a script and not a hand-written list: the manifest's only claim to being
a LEDGER rather than a to-do list is that nothing in scope can be missing from
it. That claim survives exactly as long as the row set is derived from
`git ls-files` instead of from somebody's memory, so the row set is generated
and the judgement (owner, status, evidence, revision, invalidated-by) is hand
written beside it.

The script MERGES. Everything a person wrote into a row's judgement cells is
carried forward on every re-run; a row whose file has changed since the
revision its evidence was recorded against is flipped back to `re-open`,
because clearance applies to a mechanism AT A REVISION and expires when the
mechanism moves. Rows whose file left the tree drop into a "removed" section
rather than vanishing.

Everything outside the generated block markers in MANIFEST.md is preserved
verbatim -- that is where the hand-authored cross-file obligations, the
clearance ledger and the notes live.

Usage:
    python tools/hunt_manifest.py                # regenerate in place
    python tools/hunt_manifest.py --check        # exit 1 if the file would change
    python tools/hunt_manifest.py --out other.md # write somewhere else
"""

import argparse
import os
import re
import subprocess
import sys
from collections import Counter

BEGIN = "<!-- HUNT-MANIFEST:BEGIN generated by tools/hunt_manifest.py -- do not hand-edit between these markers -->"
END = "<!-- HUNT-MANIFEST:END -->"

COLUMNS = [
    "id",
    "kind",
    "lines",
    "flags",
    "evidence required",
    "owner",
    "status",
    "evidence",
    "revision",
    "invalidated-by",
]

# Judgement cells: preserved across re-runs, never written by the generator.
KEEP = ("owner", "status", "evidence", "revision", "invalidated-by")

SCRIPT_ROOT = "Assets/_Project/Scripts"

# One entry per scoped root: (kind, predicate over a git-tracked path).
# Order matters -- the first match wins, so githooks beat the general tools glob.
SCOPE = []


def _cs_under(folder):
    prefix = "%s/%s/" % (SCRIPT_ROOT, folder)
    return lambda p: p.startswith(prefix) and p.endswith(".cs")


def _glob_dir(directory, suffixes):
    def match(p):
        if not p.startswith(directory + "/"):
            return False
        if "/" in p[len(directory) + 1:]:
            return False
        return any(p.endswith(s) for s in suffixes)
    return match


SCOPE.append(("domain", _cs_under("Domain")))
SCOPE.append(("core", _cs_under("Core")))
SCOPE.append(("data", _cs_under("Data")))
SCOPE.append(("editor", _cs_under("Editor")))
SCOPE.append(("hook", lambda p: p.startswith("tools/githooks/")))
SCOPE.append(("tool", _glob_dir("tools", (".ps1", ".py"))))
# tools/art/ holds one real generator; the manifest's whole point is that no
# tool is unlisted, so the art subfolder is scoped in rather than left out.
SCOPE.append(("tool", _glob_dir("tools/art", (".py",))))
SCOPE.append(("content", _glob_dir("Assets/_Project/ContentData", (".json",))))
SCOPE.append(("content", lambda p: p == "Assets/_Project/Resources/StanceManifest.json"))
SCOPE.append((
    "art-data",
    lambda p: p.startswith("Assets/_Project/Art/") and os.path.basename(p) == "recipe.json",
))
SCOPE.append(("art-data", _glob_dir("Assets/_Project/Art/Sheets/recipes", (".json",))))
SCOPE.append(("art-data", lambda p: p == "Assets/_Project/Art/Sheets/hand_assembled.json"))

RULE_DOCS = (
    "CLAUDE.md",
    "AUDIT.md",
    "docs/WORKFLOW.md",
    "docs/CODE_STANDARDS.md",
    "docs/CODE_MAP.md",
    "docs/CONTENT_SCHEMA.md",
    "docs/ART_PIPELINE.md",
    "docs/ARCHITECTURE.md",
    "docs/TESTING.md",
    ".claude/rules/ui.md",
    ".claude/rules/tests.md",
    ".claude/rules/tools.md",
    ".claude/rules/content.md",
)
SCOPE.append(("doc", lambda p: p in RULE_DOCS))

# A file is a seam row when its stem starts with one of these. The four seams
# carry almost every Core-to-Domain call, so their partials are flagged whole.
SEAM_PREFIXES = ("ContentDatabase", "RunManager", "RunOrchestrator", "FightSession")
SEAM_EXACT = ("SaveData", "RunSnapshot")

LIFECYCLE_TOKENS = (
    "Update",
    "LateUpdate",
    "FixedUpdate",
    "OnEnable",
    "OnDisable",
    "OnDestroy",
    "StartCoroutine",
    "IEnumerator",
)
LIFECYCLE_RE = re.compile(
    r"(?<![A-Za-z0-9_])(" + "|".join(LIFECYCLE_TOKENS) + r")(?![A-Za-z0-9_])"
)


def run_git(repo, args):
    out = subprocess.run(
        ["git"] + args, cwd=repo, capture_output=True, text=True, encoding="utf-8",
        errors="replace",
    )
    if out.returncode != 0:
        raise SystemExit("git %s failed: %s" % (" ".join(args), out.stderr.strip()))
    return out.stdout


def tracked_files(repo):
    return [line for line in run_git(repo, ["ls-files"]).splitlines() if line]


def classify(path):
    for kind, matches in SCOPE:
        if matches(path):
            return kind
    return None


def read_text(repo, path):
    full = os.path.join(repo, path)
    try:
        with open(full, "r", encoding="utf-8", errors="replace") as handle:
            return handle.read()
    except OSError:
        return None


def stem_of(path):
    name = os.path.basename(path)
    root, _ext = os.path.splitext(name)
    return root


def build_test_blob(repo, tracked):
    tests = [
        p for p in tracked
        if p.startswith(SCRIPT_ROOT + "/Tests/") and p.endswith(".cs")
    ]
    chunks = []
    for path in tests:
        text = read_text(repo, path)
        if text:
            chunks.append(text)
    return "\n".join(chunks)


def never_named(stem, blob):
    """True when the file's stem appears as a whole word nowhere in the tests.

    The stem is matched literally, dots included: `FightSession.Enemies` is a
    different obligation from `FightSession`, and a test that names the class
    is not evidence that anybody read the partial.
    """
    pattern = r"(?<![A-Za-z0-9_])" + re.escape(stem) + r"(?![A-Za-z0-9_])"
    return re.search(pattern, blob) is None


def flags_for(path, kind, stem, text, test_blob):
    flags = []
    if path.endswith(".cs") and kind in ("domain", "core", "data", "editor"):
        if never_named(stem, test_blob):
            flags.append("never-named")
    if kind == "core" and path.endswith(".cs") and text and LIFECYCLE_RE.search(text):
        flags.append("lifecycle")
    head = stem.split(".")[0]
    if head in SEAM_EXACT or any(head.startswith(p) for p in SEAM_PREFIXES):
        flags.append("seam")
    return flags


def evidence_required(flags):
    if "lifecycle" in flags or "seam" in flags:
        return "static read; asserted"
    return "static read"


def line_count(text):
    if text is None:
        return 0
    if text == "":
        return 0
    return text.count("\n") + (0 if text.endswith("\n") else 1)


def scan(repo):
    tracked = tracked_files(repo)
    test_blob = build_test_blob(repo, tracked)
    rows = []
    for path in tracked:
        kind = classify(path)
        if kind is None:
            continue
        text = read_text(repo, path)
        stem = stem_of(path)
        flags = flags_for(path, kind, stem, text, test_blob)
        rows.append({
            "id": path,
            "kind": kind,
            "lines": str(line_count(text)),
            "flags": " ".join(flags) if flags else "-",
            "evidence required": evidence_required(flags),
            "owner": "",
            "status": "open",
            "evidence": "",
            "revision": "",
            "invalidated-by": "",
        })
    rows.sort(key=lambda r: (r["kind"], r["id"]))
    return rows


def split_document(text):
    """Return (before, after) around the generated block, creating one if absent."""
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _body, tail = rest.split(END, 1)
        return head, tail
    return None, None


def parse_existing(text):
    """Read the judgement cells out of the generated block of an existing file."""
    kept = {}
    removed_order = []
    if not text:
        return kept, removed_order
    head, tail = split_document(text)
    if head is None:
        return kept, removed_order
    body = text.split(BEGIN, 1)[1].split(END, 1)[0]
    removed_columns = ["id"] + list(KEEP)
    for line in body.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) == len(COLUMNS):
            columns = COLUMNS
        elif len(cells) == len(removed_columns):
            # The removed section carries the same judgement cells with the
            # derived ones dropped. Parsed back so a file that left the tree
            # keeps its clearance instead of being forgotten on the next run.
            columns = removed_columns
        else:
            continue
        if cells[0] in ("id", "---") or set(cells[0]) == {"-"}:
            continue
        row = dict(zip(columns, cells))
        path = row["id"].strip("`")
        kept[path] = {k: row.get(k, "") for k in KEEP}
        removed_order.append(path)
    return kept, removed_order


def last_commit_for(repo, path):
    out = run_git(repo, ["log", "-1", "--format=%H", "--", path]).strip()
    return out


def merge(repo, rows, kept):
    seen = set()
    reopened = []
    added = []
    for row in rows:
        path = row["id"]
        seen.add(path)
        prior = kept.get(path)
        if prior is None:
            added.append(path)
            continue
        for key in KEEP:
            row[key] = prior.get(key, "")
        if not row["status"]:
            row["status"] = "open"
        recorded = row["revision"].strip("` ")
        if recorded:
            current = last_commit_for(repo, path)
            if current and not current.startswith(recorded) and not recorded.startswith(current):
                row["status"] = "re-open"
                reopened.append(path)
    removed = [p for p in kept if p not in seen]
    return added, reopened, sorted(removed)


def table(rows):
    lines = ["| " + " | ".join(COLUMNS) + " |"]
    lines.append("|" + "|".join(["---"] * len(COLUMNS)) + "|")
    for row in rows:
        lines.append("| " + " | ".join(row.get(c, "") for c in COLUMNS) + " |")
    return lines


def removed_block(kept, removed):
    lines = []
    lines.append("### Removed from the tree")
    lines.append("")
    if not removed:
        lines.append("None.")
        return lines
    lines.append(
        "These rows named a file that is no longer tracked. Kept with whatever "
        "evidence they carried, because a deleted file's clearance is still part "
        "of the record."
    )
    lines.append("")
    lines.append("| id | owner | status | evidence | revision | invalidated-by |")
    lines.append("|---|---|---|---|---|---|")
    for path in removed:
        prior = kept[path]
        lines.append(
            "| %s | %s | %s | %s | %s | %s |" % (
                path,
                prior.get("owner", ""),
                prior.get("status", "") or "removed",
                prior.get("evidence", ""),
                prior.get("revision", ""),
                prior.get("invalidated-by", ""),
            )
        )
    return lines


DEFAULT_SKELETON = """# Hunt manifest

Generated rows below; hand-authored sections follow the end marker and survive
every regeneration. See `docs/hunt/README.md`.

"""


def render(rows, kept, removed, head, tail):
    body = []
    body.append("")
    body.append("## Obligations, one row per scoped file")
    body.append("")
    body.append(
        "Regenerate with `python tools/hunt_manifest.py`. `owner`, `status`, "
        "`evidence`, `revision` and `invalidated-by` are written by hand and "
        "carried across re-runs; everything else is derived."
    )
    body.append("")
    body.extend(table(rows))
    body.append("")
    body.extend(removed_block(kept, removed))
    body.append("")
    return head + BEGIN + "\n" + "\n".join(body) + END + tail


def summarise(rows, added, reopened, removed):
    by_kind = Counter(r["kind"] for r in rows)
    by_status = Counter(r["status"] for r in rows)
    flags = Counter()
    for row in rows:
        if row["flags"] == "-":
            continue
        for flag in row["flags"].split():
            flags[flag] += 1
    print("rows: %d" % len(rows))
    print("by kind:   " + ", ".join("%s %d" % kv for kv in sorted(by_kind.items())))
    print("by status: " + ", ".join("%s %d" % kv for kv in sorted(by_status.items())))
    print("by flag:   " + ", ".join("%s %d" % kv for kv in sorted(flags.items())))
    print("added %d, re-opened %d, removed %d" % (len(added), len(reopened), len(removed)))
    for path in added[:20]:
        print("  + %s" % path)
    if len(added) > 20:
        print("  + ... %d more" % (len(added) - 20))
    for path in reopened:
        print("  ! re-open %s" % path)
    for path in removed:
        print("  - %s" % path)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--repo", default=None,
        help="repository root (default: the repo containing this script)",
    )
    parser.add_argument(
        "--out", default="docs/hunt/MANIFEST.md",
        help="manifest path, relative to the repo root",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="do not write; exit 1 if the file would change",
    )
    args = parser.parse_args(argv)

    repo = args.repo or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_path = os.path.join(repo, args.out)

    existing = None
    if os.path.exists(out_path):
        with open(out_path, "r", encoding="utf-8", newline="") as handle:
            existing = handle.read()

    kept, _order = parse_existing(existing)
    rows = scan(repo)
    added, reopened, removed = merge(repo, rows, kept)

    if existing is not None:
        head, tail = split_document(existing)
        if head is None:
            head, tail = existing.rstrip("\n") + "\n\n", "\n"
    else:
        head, tail = DEFAULT_SKELETON, "\n"

    text = render(rows, kept, removed, head, tail)
    text = text.replace("\r\n", "\n")

    if existing is not None and existing.replace("\r\n", "\n") == text:
        summarise(rows, added, reopened, removed)
        print("no change")
        return 0

    if args.check:
        summarise(rows, added, reopened, removed)
        print("CHANGED (--check)")
        return 1

    directory = os.path.dirname(out_path)
    if directory and not os.path.isdir(directory):
        os.makedirs(directory)
    with open(out_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    summarise(rows, added, reopened, removed)
    print("wrote %s" % args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
