using UnityEngine;
using PrincesPalace.Domain.Content;

namespace PrincesPalace.Content
{
    // One character's own combat skill, unlocked by levelling.
    //
    // Distinct from the global spell tiers in spells.json, which every
    // character shares and which only ever change the NAME and NUMBER of the
    // one Skill button. These are a character's kit: what Shawn can do that
    // nobody else can.
    //
    // Authored in Assets/_Project/ContentData/skills.json and generated by
    // ContentBuilder — never hand-authored under Resources/Content, which
    // ContentBuilder deletes wholesale on every build.
    //
    // A WRAPPER ROUND ONE VALUE, and that is the whole point. This class used
    // to restate all 34 of ResolvedSkill's fields, ContentBuilder copied them
    // across one at a time and FightEncounterAdapter copied them back — five
    // places to write the same field list, three of which decided nothing.
    // The copies dropped fields twice (`transform`, then `bookOnly`/
    // `bookTier`), which is the failure mode a mechanical 34-line copy always
    // has. Now the asset STORES the resolved value and the conversion out is
    // `definition.Data`: one field list, in ResolvedSkill, and adding a field
    // to skills.json touches RawSkillEntry, SkillEntryResolver and
    // ResolvedSkill only.
    public class SkillDefinition : ScriptableObject, IOrderedContent
    {
        // THE ONE WAY IN, and it is a setter nothing outside the Editor can
        // call. `data` was a public field: every one of the ~330 reads across
        // the tree could equally have been a write, and eight of them being
        // ContentBuilder was a convention rather than a rule. Private field,
        // public getter, internal setter -- Core grants InternalsVisibleTo to
        // PrincesPalace.Editor and to nothing else, so ContentBuilder can still
        // write it and no runtime or test assembly can.
        //
        // WHAT THIS DOES NOT BUY, said plainly because a chokepoint that is
        // half a chokepoint is worse read as a whole one: the record is a
        // class with public fields, so `definition.Data.Id = "x"` still compiles.
        // What is closed is whole-record REPLACEMENT -- swapping the catalogue
        // entry out from under everyone holding it. Field writes are covered by
        // ContentIsolationTests (behaviourally, per fight) and flagged by
        // ContentOwnershipLintTests (textually, as a diagnostic).
        [SerializeField] private ResolvedSkill data = new ResolvedSkill();

        public ResolvedSkill Data => data;

        // Editor-only, and the only assignment to `data` anywhere.
        internal void SetData(ResolvedSkill value) => data = value ?? new ResolvedSkill();

        // The one field the Get*(id) family and every content check read off
        // the asset itself rather than through `data`, so a skill looks like
        // every other definition at the lookup that finds it.
        public string id => data != null ? data.Id : "";

        // Passthrough for the same reason `id` is one -- ScreenRegistry bakes
        // icon art off content definitions by reading `.iconPath` uniformly
        // across Items/Relics/Skills, and a definition that reads through
        // `.Data.IconPath` instead would be the one exception in that sweep.
        public string iconPath => data != null ? data.IconPath : "";

        // Listed by the authored order ContentBuilder stamped on it.
        // Resources.LoadAll returns filename order, not authoring order — the
        // same trap Characters/Enemies/Upgrades/Talents/Items all guard
        // against (CLAUDE.md gotcha #4). The skill strip renders in this
        // order, so it is load-bearing here from day one.
        public int SortOrder => data != null ? data.SortOrder : 0;
    }
}
