using PrincesPalace.Domain.Combat;
using PrincesPalace.Domain.Stats;
using UnityEngine;
using PrincesPalace.Domain.Content;

namespace PrincesPalace.Content
{
    // One character's own combat skill, unlocked by levelling.
    //
    // Distinct from the global spell tiers in spells.json, which every
    // character shares and which only ever change the NAME and NUMBER of the
    // one Skill button. These are a character's kit: what Shawn can do that
    // nobody else can.
    //
    // Authored in Assets/_Project/ContentData/skills.json and generated by
    // ContentBuilder — never hand-authored under Resources/Content, which
    // ContentBuilder deletes wholesale on every build.
    public class SkillDefinition : ScriptableObject, IOrderedContent
    {
        [Tooltip("Stable identifier written into save files. Never rename this after a save exists.")]
        public string id;

        public string displayName;

        [TextArea]
        public string description;

        [Tooltip("CharacterDefinition.id of the only character who can use this.")]
        public string characterId;

        [Tooltip("Character level at which this becomes available. 1 means from the start.")]
        public int unlockLevel = 1;

        public SkillEffect effect = SkillEffect.DamageSingle;
        public SkillTargeting targeting = SkillTargeting.SingleEnemy;

        public int manaCost;

        [Tooltip("How much of the owner's signature resource a cast consumes.")]
        public int resourceCost;

        [Tooltip("Take the caster's entire signature resource instead of a fixed amount. resourceCost still applies as a minimum to cast.")]
        public bool spendsAllResource;

        [Tooltip("Added per point of signature resource actually spent.")]
        public int power;

        [Tooltip("Flat contribution: the whole amount for a heal, an offset on top of Attack for damage.")]
        public int flatAmount;

        [Tooltip("Damage only: skip the target's Defense entirely.")]
        public bool ignoresDefense;

        [Tooltip("Fixed typed damage packets. When set these REPLACE the Attack-scaled formula, and each packet is checked against the target's weakness/resistance on its own.")]
        public DamageInstance[] damageInstances = System.Array.Empty<DamageInstance>();

        [Tooltip("Resources-relative folder of this spell's animation frames (f0..fN). Empty means no visual.")]
        // See RawSkillEntry.playerSelectable. False keeps a monster's skill off
        // every player's action strip whatever its owner id says.
        public bool playerSelectable = true;

        // HOW IT LOOKS, as one serialized value. Six fields lived here and
        // each had to be copied across in ContentBuilder and again in
        // FightEncounterAdapter -- see SpellPresentation.
        public SpellPresentation vfx = new SpellPresentation();

        [Tooltip("Status this skill applies to whoever its effect already resolves against (the enemy it damaged, the ally it healed). None means it applies no status, which is most skills.")]
        public StatusEffectType appliesStatus;

        [Tooltip("Only meaningful when appliesStatus is set: whether this skill applies a status at all. Kept separate from a nullable-enum-in-the-Inspector workaround — appliesStatus defaults to Poison (index 0), which is a real status, so this bool is the actual off switch.")]
        public bool hasStatus;

        [Tooltip("Status only: damage/heal per tick for Poison/Regen, a percent for Protect/Vulnerable, unused (but authored) for Stun.")]
        public int statusMagnitude;

        [Tooltip("Status only: how many of the afflicted combatant's own turns it lasts.")]
        public int statusDuration;

        [Tooltip("Ability scores required (from base scores, talents and worn gear) before this skill can be cast at all. Zero on a score means no requirement. An unmet requirement shows greyed and uncastable rather than hiding the button.")]
        public AbilityScoreBlock requirements;

        [Tooltip("Which axis this skill's damage rides. Auto (default) derives it from the caster's own attackType -- Physical rides the weapon, everything else rides the spell. Weapon/Spell overrides that for a skill whose flavour does not match the caster's own type (a headbutt cast by a Nature-typed caster is still, narratively, physical). None rides neither axis.")]
        public ScalingAxis scalingAxis = ScalingAxis.Auto;

        [Tooltip("How many places later in the turn queue this skill knocks its target. 0 for every skill that does not touch the turn order, which is all of them but Headbutt.")]
        public int queuePushSlots;

        [Tooltip("What a Transform skill turns the caster into. Left unauthored — and rejected by the content resolver — on every other effect.")]
        public TransformGrant transform;

        // A spell that deals exactly what it says, rather than scaling off
        // the caster's Attack.
        public bool HasFixedDamage => damageInstances != null && damageInstances.Length > 0;

        // Resources.LoadAll returns filename order, not authoring order —
        // the same trap Characters/Enemies/Upgrades/Talents/Items all guard
        // against (CLAUDE.md gotcha #4). The skill strip renders in this
        // order, so it is load-bearing here from day one.
        public int sortOrder;

        public bool CostsResource => resourceCost > 0 || spendsAllResource;

        // Listed by the authored order ContentBuilder stamped on it.
        public int SortOrder => sortOrder;
    }
}
