using UnityEngine;
using PrincesPalace.Domain.Content;

namespace PrincesPalace.Content
{
    // One character's own combat skill, unlocked by levelling.
    //
    // Distinct from the global spell tiers in spells.json, which every
    // character shares and which only ever change the NAME and NUMBER of the
    // one Skill button. These are a character's kit: what Shawn can do that
    // nobody else can.
    //
    // Authored in Assets/_Project/ContentData/skills.json and generated by
    // ContentBuilder — never hand-authored under Resources/Content, which
    // ContentBuilder deletes wholesale on every build.
    //
    // A WRAPPER ROUND ONE VALUE, and that is the whole point. This class used
    // to restate all 34 of ResolvedSkill's fields, ContentBuilder copied them
    // across one at a time and FightEncounterAdapter copied them back — five
    // places to write the same field list, three of which decided nothing.
    // The copies dropped fields twice (`transform`, then `bookOnly`/
    // `bookTier`), which is the failure mode a mechanical 34-line copy always
    // has. Now the asset STORES the resolved value and the conversion out is
    // `definition.data`: one field list, in ResolvedSkill, and adding a field
    // to skills.json touches RawSkillEntry, SkillEntryResolver and
    // ResolvedSkill only.
    public class SkillDefinition : ScriptableObject, IOrderedContent
    {
        public ResolvedSkill data = new ResolvedSkill();

        // The one field the Get*(id) family and every content check read off
        // the asset itself rather than through `data`, so a skill looks like
        // every other definition at the lookup that finds it.
        public string id => data != null ? data.Id : "";

        // Listed by the authored order ContentBuilder stamped on it.
        // Resources.LoadAll returns filename order, not authoring order — the
        // same trap Characters/Enemies/Upgrades/Talents/Items all guard
        // against (CLAUDE.md gotcha #4). The skill strip renders in this
        // order, so it is load-bearing here from day one.
        public int SortOrder => data != null ? data.SortOrder : 0;
    }
}
