using PrincesPalace.Domain.Content;
using UnityEngine;

namespace PrincesPalace.Content
{
    // A permanent, account-wide Divine Principality upgrade. Deliberately
    // separate from talents: talents are per-character build power, these are
    // profile-wide, so the two never compete for the same currency.
    //
    // Authored in Assets/_Project/ContentData/upgrades.json and generated by
    // ContentBuilder -- never hand-edited under Resources/Content, which
    // ContentBuilder deletes wholesale on every build.
    //
    // A WRAPPER ROUND ONE VALUE, like the other eight. This one was the last
    // holdout: it had no Raw/Resolved pair at all, so ContentBuilder set its
    // six fields directly from positional arguments and nothing validated any
    // of them. The asset stores the resolved value now.
    public class UpgradeDefinition : ScriptableObject, IOrderedContent
    {
        public ResolvedUpgrade data = new ResolvedUpgrade();

        // The one field the Get*(id) family and every content check read off
        // the asset itself rather than through `data`.
        public string id => data != null ? data.Id : "";

        // Listed by the authored order ContentBuilder stamped on it.
        // Resources.LoadAll returns filename order, not authoring order.
        public int SortOrder => data != null ? data.SortOrder : 0;
    }
}
